export let globe = [
  {
    area: "Arctic Ocean",
    type: "ocean",
    objects: [
      {
        name: "NORTH POLE FLAG",
        article: "The",
        description:
          "A Russian flag on the sea floor is the only permanent marker of the planet's geographic north pole.",
      },
      {
        name: "LOST PENGUIN",
        article: "A",
        description:
          "A funny-looking flightless bird. This one explains that he normally lives at the south pole, but nothing is stopping him from traveling.",
      },
      {
        name: "PETROLEUM",
        article: "Some",
        description: "A viscous, yellowish-black liquid used to power chainsaws.",
      },
    ],
    neighbors: ["Canada", "Greenland", "Iceland", "Norway", "Russia", "United States"],
  },
  {
    area: "Pacific Ocean",
    type: "ocean",
    description:
      "The Pacific Ocean was first discovered by single-celled organisms billions of years ago, but it wasn't explored until much later, by fish.",
    objects: [
      {
        name: "WATER",
        description: "A pile of water, currently in liquid form",
        article: "A lot of",
      },
    ],
    neighbors: [
      "Australia",
      "Brunei",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Colombia",
      "Costa Rica",
      "East Timor",
      "Easter Island",
      "Ecuador",
      "El Salvador",
      "Federated States of Micronesia",
      "Fiji",
      "Guatemala",
      "Honduras",
      "Hong Kong",
      "Indonesia",
      "Japan",
      "Kiribati",
      "Malaysia",
      "Marshall Islands",
      "Mexico",
      "Nauru",
      "New Zealand",
      "Nicaragua",
      "North Korea",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Peru",
      "Philippines",
      "Russia",
      "Samoa",
      "Singapore",
      "Solomon Islands",
      "South Korea",
      "Taiwan",
      "Thailand",
      "Tonga",
      "Tuvalu",
      "United States",
      "Vanuatu",
      "Vietnam",
      "Wallis Island",
    ],
  },
  {
    area: "Atlantic Ocean",
    type: "ocean",
    neighbors: [
      "Albania",
      "Algeria",
      "Angola",
      "Antigua and Barbuda",
      "Argentina",
      "Bahamas",
      "Barbados",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bermuda",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Chile",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Cyprus",
      "Democratic Republic of the Congo",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Egypt",
      "England",
      "Equatorial Guinea",
      "Estonia",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea-Bissau",
      "Guinea",
      "Guyana",
      "Haiti",
      "Honduras",
      "Iceland",
      "Ireland",
      "Ireland",
      "Israel",
      "Italy",
      "Ivory Coast",
      "Jamaica",
      "Latvia",
      "Lebanon",
      "Liberia",
      "Libya",
      "Lithuania",
      "Malta",
      "Mauritania",
      "Mexico",
      "Monaco",
      "Montenegro",
      "Morocco",
      "Namibia",
      "Netherlands",
      "Nicaragua",
      "Nigeria",
      "Norway",
      "Palestine",
      "Panama",
      "Poland",
      "Portugal",
      "Republic of the Congo",
      "Romania",
      "Russia",
      "Russia",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "São Tomé and Príncipe",
      "Scotland",
      "Senegal",
      "Sierra Leone",
      "Slovenia",
      "South Africa",
      "Spain",
      "Suriname",
      "Svalbard",
      "Sweden",
      "Syria",
      "Togo",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkey",
      "Ukraine",
      "United States",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    area: "Indian Ocean",
    type: "ocean",
    neighbors: [
      "Australia",
      "Bahrain",
      "Bangladesh",
      "Comoros",
      "Djibouti",
      "East Timor",
      "Egypt",
      "Eritrea",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Jordan",
      "Kenya",
      "Kuwait",
      "Madagascar",
      "Malaysia",
      "Maldives",
      "Mauritius",
      "Mozambique",
      "Myanmar",
      "Oman",
      "Pakistan",
      "Qatar",
      "Saudi Arabia",
      "Seychelles",
      "Singapore",
      "Somalia",
      "South Africa",
      "Sri Lanka",
      "Sudan",
      "Tanzania",
      "Thailand",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    area: "Abkhazia",
    type: "country",
    neighbors: ["Russia", "Georgia"],
  },
  {
    area: "Afghanistan",
    type: "country",
    neighbors: ["China", "Iran", "Pakistan", "Tajikistan", "Turkmenistan", "Uzbekistan"],
  },
  {
    area: "Albania",
    type: "country",
    neighbors: ["Greece", "Kosovo", "North Macedonia", "Montenegro", "Atlantic Ocean"],
  },
  {
    area: "Algeria",
    type: "country",
    neighbors: [
      "Libya",
      "Mali",
      "Mauritania",
      "Morocco",
      "Niger",
      "Tunisia",
      "Western Sahara",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Andorra",
    type: "country",
    neighbors: ["France", "Spain"],
  },
  {
    area: "Angola",
    type: "country",
    neighbors: [
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "Namibia",
      "Zambia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Antigua and Barbuda",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Argentina",
    type: "country",
    neighbors: ["Bolivia", "Brazil", "Chile", "Library of Babel", "Paraguay", "Uruguay"],
  },
  {
    area: "Armenia",
    type: "country",
    neighbors: ["Azerbaijan", "Georgia", "Iran", "Turkey"],
  },
  {
    area: "Australia",
    type: "country",
    neighbors: ["Pacific Ocean", "Indian Ocean"],
  },
  {
    area: "Austria",
    type: "country",
    neighbors: [
      "Czech Republic",
      "Germany",
      "Hungary",
      "Italy",
      "Liechtenstein",
      "Slovakia",
      "Slovenia",
      "Switzerland",
    ],
  },
  {
    area: "Azerbaijan",
    type: "country",
    neighbors: ["Armenia", "Georgia", "Iran", "Russia", "Turkey"],
  },
  {
    area: "Bahamas",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Bahrain",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Bangladesh",
    type: "country",
    neighbors: ["India", "Myanmar", "Indian Ocean"],
  },
  {
    area: "Barbados",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Belarus",
    type: "country",
    neighbors: ["Latvia", "Lithuania", "Poland", "Russia", "Ukraine"],
  },
  {
    area: "Belgium",
    type: "country",
    neighbors: ["Atlantic Ocean", "France", "Germany", "Luxembourg", "Netherlands"],
  },
  {
    area: "Belize",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guatemala", "Mexico"],
  },
  {
    area: "Benin",
    type: "country",
    neighbors: ["Atlantic Ocean", "Burkina Faso", "Niger", "Nigeria", "Togo"],
  },
  {
    area: "Bermuda",
    type: "special",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Bhutan",
    type: "country",
    neighbors: ["China", "India"],
  },
  {
    area: "Bolivia",
    type: "country",
    neighbors: ["Argentina", "Brazil", "Chile", "Paraguay", "Peru"],
  },
  {
    area: "Bosnia and Herzegovina",
    type: "country",
    neighbors: ["Atlantic Ocean", "Croatia", "Montenegro", "Serbia"],
  },
  {
    area: "Botswana",
    type: "country",
    neighbors: ["Namibia", "South Africa", "Zambia", "Zimbabwe"],
  },
  {
    area: "Brazil",
    type: "country",
    neighbors: [
      "Argentina",
      "Atlantic Ocean",
      "Bolivia",
      "Colombia",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    area: "Brunei",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Bulgaria",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Greece",
      "North Macedonia",
      "Romania",
      "Serbia",
      "Turkey",
    ],
  },
  {
    area: "Burkina Faso",
    type: "country",
    neighbors: ["Benin", "Côte d'Ivoire", "Ghana", "Mali", "Niger", "Togo"],
  },
  {
    area: "Burundi",
    type: "country",
    neighbors: ["Democratic Republic of the Congo", "Rwanda", "Tanzania"],
  },
  {
    area: "Cambodia",
    type: "country",
    neighbors: ["Laos", "Pacific Ocean", "Thailand", "Vietnam"],
  },
  {
    area: "Cameroon",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Central African Republic",
      "Chad",
      "Equatorial Guinea",
      "Gabon",
      "Nigeria",
      "Republic of the Congo",
    ],
  },
  {
    area: "Canada",
    description:
      "A massive country, covered in endless marches of snow. At first, it seems sparsely populated, but as you scan the coastlines, you notice sizable clusters of gentle, industrious citizens (known as 'canadians' or 'canucks') living at the eastern and western edges of the continent.",
    type: "country",
    objects: [
      {
        name: "ZINC",
        article: "Some",
        description:
          "A lump of silver metal. Also known as philosopher's wool, it is useful for weather-proofing everything from fences to noses. When alloyed with copper, it can be used to make trumpets.",
      },
    ],
    neighbors: ["Arctic Ocean", "Atlantic Ocean", "Pacific Ocean", "United States"],
  },
  {
    area: "Cape Verde",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Central African Republic",
    type: "country",
    neighbors: [
      "Cameroon",
      "Chad",
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "South Sudan",
      "Sudan",
    ],
  },
  {
    area: "Chad",
    type: "country",
    neighbors: [
      "Cameroon",
      "Central African Republic",
      "Libya",
      "Niger",
      "Nigeria",
      "Sudan",
    ],
  },
  {
    area: "Chile",
    type: "country",
    neighbors: ["Argentina", "Atlantic Ocean", "Bolivia", "Pacific Ocean", "Peru"],
  },
  {
    area: "China",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Bhutan",
      "Hong Kong",
      "India",
      "Kazakhstan",
      "Kyrgyzstan",
      "Laos",
      "Macau",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "North Korea",
      "Pacific Ocean",
      "Pakistan",
      "Russia",
      "Tajikistan",
      "Vietnam",
    ],
  },
  {
    area: "Colombia",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Brazil",
      "Ecuador",
      "Pacific Ocean",
      "Panama",
      "Peru",
      "Venezuela",
    ],
  },
  {
    area: "Comoros",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Democratic Republic of the Congo",
    type: "country",
    neighbors: [
      "Angola",
      "Atlantic Ocean",
      "Burundi",
      "Central African Republic",
      "Republic of the Congo",
      "Rwanda",
      "South Sudan",
      "Tanzania",
      "Uganda",
      "Zambia",
    ],
  },
  {
    area: "Republic of the Congo",
    type: "country",
    neighbors: [
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Democratic Republic of the Congo",
      "Gabon",
    ],
  },
  {
    area: "Costa Rica",
    type: "country",
    neighbors: ["Atlantic Ocean", "Nicaragua", "Pacific Ocean", "Panama"],
  },
  {
    area: "Côte d'Ivoire",
    type: "country",
    neighbors: ["Atlantic Ocean", "Burkina Faso", "Ghana", "Guinea", "Liberia", "Mali"],
  },
  {
    area: "Croatia",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Bosnia and Herzegovina",
      "Hungary",
      "Montenegro",
      "Serbia",
      "Slovenia",
    ],
  },
  {
    area: "Cuba",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Cyprus",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Czech Republic",
    type: "country",
    neighbors: ["Austria", " Germany", "Poland", " Slovakia"],
  },
  {
    area: "Denmark",
    type: "country",
    neighbors: ["Germany", "Atlantic Ocean"],
  },
  {
    area: "Djibouti",
    type: "country",
    neighbors: ["Eritrea", "Ethiopia", "Indian Ocean", "Somaliland"],
  },
  {
    area: "Dominica",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Dominican Republic",
    type: "country",
    neighbors: ["Atlantic Ocean", "Haiti"],
  },
  {
    area: "Easter Island",
    type: "special",
    neighbors: ["Pacific Ocean"],
    objects: [
      {
        name: "MOAI STATUE",
        article: "A",
        description: "A massive stone monolith in the shape of a person.",
      },
      {
        name: "SIROLIMUS",
        article: "A vial of",
        description:
          "This immunosuppressant drug is used to prevent organ transplant rejection. As everybody already knows, sirolimus was discovered on Easter Island, in a soil sample containing streptomyces hygroscopicus.",
      },
    ],
  },
  {
    area: "East Timor",
    type: "country",
    neighbors: ["Indonesia", "Indian Ocean", "Pacific Ocean"],
  },
  {
    area: "Ecuador",
    type: "country",
    neighbors: ["Colombia", "Pacific Ocean", "Peru"],
  },
  {
    area: "Egypt",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Gaza Strip",
      "Indian Ocean",
      "Israel",
      "Libya",
      "Sudan",
    ],
  },
  {
    area: "El Salvador",
    type: "country",
    neighbors: ["Guatemala", "Honduras", "Pacific Ocean"],
  },
  {
    area: "England",
    type: "country",
    neighbors: ["Atlantic Ocean", "Scotland", "Wales"],
  },
  {
    area: "Equatorial Guinea",
    type: "country",
    neighbors: ["Atlantic Ocean", "Cameroon", "Gabon"],
  },
  {
    area: "Eritrea",
    type: "country",
    neighbors: ["Djibouti", "Ethiopia", "Indian Ocean", "Sudan"],
  },
  {
    area: "Estonia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Latvia", "Russia"],
  },
  {
    area: "Eswatini",
    type: "country",
    neighbors: ["Mozambique", "South Africa"],
  },
  {
    area: "Ethiopia",
    type: "country",
    neighbors: ["Djibouti", "Eritrea", "Kenya", "Somalia", "South Sudan", "Sudan"],
  },
  {
    area: "Fiji",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Finland",
    type: "country",
    neighbors: ["Atlantic Ocean", "Norway", "Sweden", "Russia"],
  },
  {
    area: "France",
    type: "country",
    neighbors: [
      "Andorra",
      "Atlantic Ocean",
      "Belgium",
      "Germany",
      "Italy",
      "Luxembourg",
      "Monaco",
      "Spain",
      "Switzerland",
    ],
  },
  {
    area: "Gabon",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Cameroon",
      "Equatorial Guinea",
      "Republic of the Congo",
    ],
  },
  {
    area: "Gambia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Senegal"],
  },
  {
    area: "Georgia",
    type: "country",
    neighbors: [
      "Abkhazia",
      "Armenia",
      "Atlantic Ocean",
      "Azerbaijan",
      "Russia",
      "South Ossetia",
      "Turkey",
    ],
  },
  {
    area: "Germany",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Austria",
      "Belgium",
      "Czech Republic",
      "Denmark",
      "France",
      "Luxembourg",
      "Netherlands",
      "Poland",
      "Switzerland",
    ],
  },
  {
    area: "Ghana",
    type: "country",
    neighbors: ["Atlantic Ocean", "Burkina Faso", "Côte d'Ivoire", "Togo"],
  },
  {
    area: "Greece",
    type: "country",
    neighbors: ["Albania", "Atlantic Ocean", "Bulgaria", "North Macedonia", "Turkey"],
  },
  {
    area: "Greenland",
    type: "country",
    description:
      "Fans of large islands have found what they're looking for: Greenland is the biggest island in the entire world, bar none. It is cold here. In the distance, you see a factory powering the economy by exporting shrimp and halibut, and groups of tourists enjoying themselves in the capitol city of Nuuk.",
    objects: [
      {
        name: "SHRIMP",
        article: "Some",
        description:
          "A crustacean stares up at you with long, gross eyes on disgusting, hateful stalks.",
      },
      {
        name: "RUNESTONE",
        article: "A",
        description:
          "This black chunk of star-metal is covered in ancient runes that throb with eldritch power.",
      },
    ],
    neighbors: ["Arctic Ocean", "Atlantic Ocean"],
  },
  {
    area: "Grenada",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Guatemala",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Belize",
      "El Salvador",
      "Honduras",
      "Mexico",
      "Pacific Ocean",
    ],
  },
  {
    area: "Guinea",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Côte d'Ivoire",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Senegal",
      "Sierra Leone",
    ],
  },
  {
    area: "Guinea-Bissau",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guinea", "Senegal"],
  },
  {
    area: "Guyana",
    type: "country",
    neighbors: ["Atlantic Ocean", "Brazil", "Suriname", "Venezuela"],
  },
  {
    area: "Haiti",
    type: "country",
    neighbors: ["Atlantic Ocean", "Dominican Republic"],
  },
  {
    area: "Honduras",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "El Salvador",
      "Guatemala",
      "Nicaragua",
      "Pacific Ocean",
    ],
  },
  {
    area: "Hong Kong",
    type: "special",
    neighbors: ["China", "Pacific Ocean"],
  },
  {
    area: "Hungary",
    type: "country",
    neighbors: [
      "Austria",
      "Croatia",
      "Romania",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Ukraine",
    ],
  },
  {
    area: "Iceland",
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean"],
  },
  {
    area: "India",
    type: "country",
    neighbors: [
      "Bangladesh",
      "Bhutan",
      "China",
      "Indian Ocean",
      "Myanmar",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
    ],
  },
  {
    area: "Indonesia",
    type: "country",
    neighbors: [
      "East Timor",
      "Indian Ocean",
      "Malaysia",
      "Pacific Ocean",
      "Papua New Guinea",
    ],
  },
  {
    area: "Iran",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Indian Ocean",
      "Iraq",
      "Pakistan",
      "Turkey",
      "Turkmenistan",
    ],
  },
  {
    area: "Iraq",
    type: "country",
    neighbors: [
      "Indian Ocean",
      "Iran",
      "Jordan",
      "Kuwait",
      "Saudi Arabia",
      "Syria",
      "Turkey",
    ],
  },
  {
    area: "Ireland",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Israel",
    type: "country",
    neighbors: ["Atlantic Ocean", "Egypt", "Indian Ocean", "Jordan", "Lebanon", "Syria"],
  },
  {
    area: "Italy",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Austria",
      "France",
      "San Marino",
      "Slovenia",
      "Switzerland",
      "Vatican City",
    ],
  },
  {
    area: "Jamaica",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Japan",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Jordan",
    type: "country",
    neighbors: ["Indian Ocean", "Iraq", "Israel", "Saudi Arabia", "Syria"],
  },
  {
    area: "Kazakhstan",
    type: "country",
    neighbors: ["China", "Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
  },
  {
    area: "Kenya",
    type: "country",
    neighbors: [
      "Ethiopia",
      "Indian Ocean",
      "Somalia",
      "South Sudan",
      "Tanzania",
      "Uganda",
    ],
  },
  {
    area: "Kiribati",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Library of Babel",
    description:
      "You are in a hexagonal gallery, surrounding an air shaft. On four sides of the hexagon there are book shelves filled with many similar-looking volumes. The other two sides lead into narrow hallways, beyond which are more galleries exactly like this one.",
    objects: [
      {
        name: "BOOK",
        article: "A",
        description: "It <em>seems</em> to be gibberish.",
      },
    ],
    type: "special",
    neighbors: ["Argentina", "Library of Babel"],
  },
  {
    area: "North Korea",
    type: "country",
    neighbors: ["China", "Pacific Ocean", "South Korea", "Russia"],
  },
  {
    area: "South Korea",
    type: "country",
    neighbors: ["North Korea", "Pacific Ocean"],
  },
  {
    area: "Kosovo",
    type: "country",
    neighbors: ["Albania", "Montenegro", "North Macedonia", "Serbia"],
  },
  {
    area: "Kuwait",
    type: "country",
    neighbors: ["Indian Ocean", "Iraq", "Saudi Arabia"],
  },
  {
    area: "Kyrgyzstan",
    type: "country",
    neighbors: ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
  },
  {
    area: "Laos",
    type: "country",
    neighbors: ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
  },
  {
    area: "Latvia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Belarus", "Estonia", "Lithuania", "Russia"],
  },
  {
    area: "Lebanon",
    type: "country",
    neighbors: ["Atlantic Ocean", "Israel", "Syria"],
  },
  {
    area: "Lesotho",
    type: "country",
    neighbors: ["South Africa"],
  },
  {
    area: "Liberia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guinea", "Côte d'Ivoire", "Sierra Leone"],
  },
  {
    area: "Libya",
    type: "country",
    neighbors: [
      "Algeria",
      "Atlantic Ocean",
      "Chad",
      "Egypt",
      "Niger",
      "Sudan",
      "Tunisia",
    ],
  },
  {
    area: "Liechtenstein",
    type: "country",
    neighbors: ["Austria", "Switzerland"],
  },
  {
    area: "Lithuania",
    type: "country",
    neighbors: ["Atlantic Ocean", "Belarus", "Latvia", "Poland", "Russia"],
  },
  {
    area: "Luxembourg",
    type: "country",
    neighbors: ["Belgium", "France", "Germany"],
  },
  {
    area: "Macau",
    type: "country",
    neighbors: ["China", "Pacific Ocean"],
  },
  {
    area: "Madagascar",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Madeira",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Malawi",
    type: "country",
    neighbors: ["Mozambique", "Tanzania", "Zambia"],
  },
  {
    area: "Malaysia",
    type: "country",
    neighbors: ["Brunei", "Indian Ocean", "Indonesia", "Pacific Ocean", "Thailand"],
  },
  {
    area: "Maldives",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Mali",
    type: "country",
    neighbors: [
      "Algeria",
      "Burkina Faso",
      "Côte d'Ivoire",
      "Guinea",
      "Mauritania",
      "Niger",
      "Senegal",
    ],
  },
  {
    area: "Malta",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Marshall Islands",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Mauritania",
    type: "country",
    neighbors: ["Algeria", "Atlantic Ocean", "Mali", "Senegal", "Western Sahara"],
  },
  {
    area: "Mauritius",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Mexico",
    type: "country",
    description:
      "It's hot here. As you pause for a moment to wipe the sweat from your brow, you can't help but see that Mexico is a country with many different people in it. Soon, your curiosity gets the better of you, and you stop in the shade of a SAGUARO CACTUS to watch them do the different kinds of things they are doing. You notice that sometimes they meet with success, but other times they do not. Yet, despite it all, they keep doing those things. What a remarkable country.",
    objects: [
      {
        name: "SAGUARO CACTUS",
        article: "A",
        description:
          'You must hold this cactus very cautiously, since it is covered in prickly, needlelike spines, called "spines" (or "needles") that can prick an incautious holder. This particular specimen is 12 feet tall, and 150 years old, making it both taller and older than any living basketball player.',
      },
      {
        name: "TEOTIHUACAN",
        article: "The city of",
        description:
          "A ruined complex with a stepped pyramid. You see that it was built by an ancient people, due to being old.",
      },
      {
        name: "AXOLOTL",
        article: "An",
        description:
          "A peculiar sort of salamander creature, native only to a few lakes around Mexico City. Unlike most people, it can regenerate its limbs.",
      },
      {
        name: "SPEARTHROWER OWL",
        article: "The",
        description:
          "A stone glyph, carved into the  shape of an owl holding a spear, it is the icon of an ancient Mayan king.",
      },
      {
        name: "TACO",
        article: "A",
        description:
          "It is an open-faced sandwich with meat, vegetables, and so on, traditionally eaten on Tuesdays.",
      },
    ],
    neighbors: [
      "Atlantic Ocean",
      "Belize",
      "Guatemala",
      "Pacific Ocean",
      "United States",
    ],
  },
  {
    area: "Federated States of Micronesia",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Moldova",
    type: "country",
    neighbors: ["Romania", "Ukraine"],
  },
  {
    area: "Monaco",
    type: "country",
    neighbors: ["Atlantic Ocean", "France"],
  },
  {
    area: "Mongolia",
    type: "country",
    neighbors: ["China", "Russia"],
  },
  {
    area: "Montenegro",
    type: "country",
    neighbors: [
      "Albania",
      "Atlantic Ocean",
      "Bosnia and Herzegovina",
      "Croatia",
      "Kosovo",
      "Serbia",
    ],
  },
  {
    area: "Morocco",
    type: "country",
    neighbors: ["Algeria", "Atlantic Ocean", "Western Sahara", "Spain"],
  },
  {
    area: "Mozambique",
    type: "country",
    neighbors: [
      "Eswatini",
      "Indian Ocean",
      "Malawi",
      "South Africa",
      "Tanzania",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    area: "Myanmar",
    type: "country",
    neighbors: ["Bangladesh", "China", "India", "Indian Ocean", "Laos", "Thailand"],
  },
  {
    area: "Namibia",
    type: "country",
    neighbors: ["Angola", "Atlantic Ocean", "Botswana", "South Africa", "Zambia"],
  },
  {
    area: "Nauru",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Nepal",
    type: "country",
    neighbors: ["China", "India"],
  },
  {
    area: "Netherlands",
    type: "country",
    neighbors: ["Atlantic Ocean", "Belgium", "Germany", "Saint Martin", "France"],
  },
  {
    area: "New Zealand",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Nicaragua",
    type: "country",
    neighbors: ["Atlantic Ocean", "Costa Rica", "Honduras", "Pacific Ocean"],
  },
  {
    area: "Niger",
    type: "country",
    neighbors: ["Algeria", "Benin", "Burkina Faso", "Chad", "Libya", "Mali", "Nigeria"],
  },
  {
    area: "Nigeria",
    type: "country",
    neighbors: ["Atlantic Ocean", "Benin", "Cameroon", "Chad", "Niger"],
  },
  {
    area: "North Macedonia",
    type: "country",
    neighbors: ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
  },
  {
    area: "Norway",
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean", "Finland", "Sweden", "Russia"],
  },
  {
    area: "Oman",
    type: "country",
    neighbors: ["Indian Ocean", "Saudi Arabia", "United Arab Emirates", "Yemen"],
  },
  {
    area: "Pakistan",
    type: "country",
    neighbors: ["Afghanistan", "India", "Indian Ocean", "Iran", "China"],
  },
  {
    area: "Palau",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Palestine",
    type: "country",
    neighbors: ["Atlantic Ocean", "Egypt", "Israel", "Jordan"],
  },
  {
    area: "Panama",
    type: "country",
    neighbors: ["Atlantic Ocean", "Colombia", "Costa Rica", "Pacific Ocean"],
  },
  {
    area: "Papua New Guinea",
    type: "country",
    neighbors: ["Indonesia", "Pacific Ocean"],
  },
  {
    area: "Paraguay",
    type: "country",
    neighbors: ["Argentina", "Bolivia", "Brazil"],
  },
  {
    area: "Peru",
    type: "country",
    neighbors: ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Pacific Ocean"],
  },
  {
    area: "Philippines",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Poland",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Belarus",
      "Czech Republic",
      "Germany",
      "Lithuania",
      "Russia",
      "Slovakia",
      "Ukraine",
    ],
  },
  {
    area: "Portugal",
    type: "country",
    neighbors: ["Atlantic Ocean", "Spain"],
  },
  {
    area: "Qatar",
    type: "country",
    neighbors: ["Indian Ocean", "Saudi Arabia"],
  },
  {
    area: "Romania",
    type: "country",
    neighbors: ["Atlantic Ocean", "Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
  },
  {
    area: "Russia",
    type: "country",
    neighbors: [
      "Abkhazia",
      "Arctic Ocean",
      "Atlantic Ocean",
      "Azerbaijan",
      "Belarus",
      "China",
      "Estonia",
      "Finland",
      "Georgia",
      "Kazakhstan",
      "Latvia",
      "Lithuania",
      "Mongolia",
      "North Korea",
      "Norway",
      "Pacific Ocean",
      "Poland",
      "South Ossetia",
      "Ukraine",
    ],
  },
  {
    area: "Rwanda",
    type: "country",
    neighbors: ["Burundi", "Democratic Republic of the Congo", "Tanzania", "Uganda"],
  },
  {
    area: "Saint Kitts and Nevis",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saint Lucia",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saint Vincent and the Grenadines",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Samoa",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "San Marino",
    type: "country",
    neighbors: ["Italy"],
  },
  {
    area: "São Tomé and Príncipe",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saudi Arabia",
    type: "country",
    neighbors: [
      "Indian Ocean",
      "Iraq",
      "Jordan",
      "Kuwait",
      "Oman",
      "Qatar",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    area: "Scotland",
    type: "country",
    neighbors: ["Atlantic Ocean", "England"],
  },
  {
    area: "Senegal",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Gambia",
      "Guinea-Bissau",
      "Guinea",
      "Mali",
      "Mauritania",
    ],
  },
  {
    area: "Serbia",
    type: "country",
    neighbors: [
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Hungary",
      "Kosovo",
      "Montenegro",
      "North Macedonia",
      "Romania",
    ],
  },
  {
    area: "Seychelles",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Sierra Leone",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guinea", "Liberia"],
  },
  {
    area: "Singapore",
    type: "country",
    neighbors: ["Indian Ocean", "Pacific Ocean"],
  },
  {
    area: "Slovakia",
    type: "country",
    neighbors: ["Austria", "Czech Republic", "Hungary", "Poland", "Ukraine"],
  },
  {
    area: "Slovenia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Austria", "Croatia", "Italy", "Hungary"],
  },
  {
    area: "Solomon Islands",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Somalia",
    type: "country",
    neighbors: ["Djibouti", "Ethiopia", "Indian Ocean", "Kenya"],
  },
  {
    area: "South Africa",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Botswana",
      "Eswatini",
      "Indian Ocean",
      "Lesotho",
      "Mozambique",
      "Namibia",
      "Zimbabwe",
    ],
  },
  {
    area: "South Ossetia",
    type: "country",
    neighbors: ["Russia", "Georgia"],
  },
  {
    area: "South Sudan",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Democratic Republic of the Congo",
      "Ethiopia",
      "Kenya",
      "Sudan",
      "Uganda",
    ],
  },
  {
    area: "Spain",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Andorra",
      "France",
      "Portugal",
      "Gibraltar",
      "Morocco",
    ],
  },
  {
    area: "Sri Lanka",
    type: "country",
    neighbors: ["India", "Indian Ocean"],
  },
  {
    area: "Sudan",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Chad",
      "Egypt",
      "Eritrea",
      "Ethiopia",
      "Indian Ocean",
      "Libya",
      "South Sudan",
    ],
  },
  {
    area: "Suriname",
    type: "country",
    neighbors: ["Atlantic Ocean", "Brazil", "French Guiana", "Guyana"],
  },
  {
    area: "Svalbard",
    type: "special",
    neighbors: ["Atlantic Ocean", "Brazil", "French Guiana", "Guyana"],
  },
  {
    area: "Sweden",
    type: "country",
    neighbors: ["Atlantic Ocean", "Finland", "Norway"],
  },
  {
    area: "Switzerland",
    type: "country",
    neighbors: ["Austria", "France", "Germany", "Italy", "Liechtenstein"],
  },
  {
    area: "Syria",
    type: "country",
    neighbors: ["Atlantic Ocean", "Iraq", "Israel", "Jordan", "Lebanon", "Turkey"],
  },
  {
    area: "Taiwan",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Tajikistan",
    type: "country",
    neighbors: ["Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"],
  },
  {
    area: "Tanzania",
    type: "country",
    neighbors: [
      "Burundi",
      "Democratic Republic of the Congo",
      "Indian Ocean",
      "Kenya",
      "Malawi",
      "Mozambique",
      "Rwanda",
      "Uganda",
      "Zambia",
    ],
  },
  {
    area: "Tasmania",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Thailand",
    type: "country",
    neighbors: [
      "Cambodia",
      "Indian Ocean",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Pacific Ocean",
    ],
  },
  {
    area: "Togo",
    type: "country",
    neighbors: ["Benin", "Burkina Faso", "Ghana"],
  },
  {
    area: "Tonga",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Trinidad and Tobago",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Tunisia",
    type: "country",
    neighbors: ["Algeria", "Libya"],
  },
  {
    area: "Turkey",
    type: "country",
    neighbors: [
      "Armenia",
      "Atlantic Ocean",
      "Azerbaijan",
      "Bulgaria",
      "Georgia",
      "Greece",
      "Iran",
      "Iraq",
      "Syria",
    ],
  },
  {
    area: "Turkmenistan",
    type: "country",
    neighbors: ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan"],
  },
  {
    area: "Tuvalu",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Uganda",
    type: "country",
    neighbors: [
      "Democratic Republic of the Congo",
      "Kenya",
      "Rwanda",
      "South Sudan",
      "Tanzania",
    ],
  },
  {
    area: "Ukraine",
    type: "country",
    neighbors: [
      "Belarus",
      "Hungary",
      "Moldova",
      "Poland",
      "Romania",
      "Russia",
      "Slovakia",
    ],
  },
  {
    area: "United Arab Emirates",
    type: "country",
    neighbors: ["Indian Ocean", "Oman", "Saudi Arabia"],
  },
  {
    area: "United States",
    description:
      'A large and diverse country, it is home to the famous "50 state quarters" phenomenon of the early 2000s. You see a BALD EAGLE fishing the many lakes, rivers, and ponds here.',
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean", "Canada", "Mexico", "Pacific Ocean"],
    objects: [
      {
        name: "GRAND CANYON",
        article: "The",
        description: "A canyon, roughly 277 miles long, 18 miles wide, and 1 mile deep.",
      },
      {
        name: "LIBERTY BELL",
        article: "The",
        description: "A large bell containing the sound of freedom",
      },
      {
        name: "BALD EAGLE",
        article: "A",
        description:
          "This large bird has a white head, dark body, yellow beak, and pink tongue. Most often found in wooded areas, they can sometimes be seen flying in front of waving flags or at fireworks shows. In addition to fish, bald eagles are the primary predator of raccoons.",
      },
      {
        name: "IDAHO POTATO",
        article: "An",
        description: "A small tuber, covered in dirt.",
      },
    ],
  },
  {
    area: "Uruguay",
    type: "country",
    neighbors: ["Argentina", "Atlantic Ocean", "Brazil"],
  },
  {
    area: "Uzbekistan",
    type: "country",
    neighbors: ["Afghanistan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan"],
  },
  {
    area: "Vanuatu",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Vatican City",
    type: "country",
    neighbors: ["Italy"],
  },
  {
    area: "Venezuela",
    type: "country",
    neighbors: ["Atlantic Ocean", "Brazil", "Colombia", "Guyana"],
  },
  {
    area: "Vietnam",
    type: "country",
    neighbors: ["Cambodia", "China", "Laos", "Pacific Ocean"],
  },
  {
    area: "Wallis Island",
    type: "country",
    neighbors: ["Pacific Ocean"],
    objects: [
      {
        name: "TALIETUMU",
        article: "A pile of rocks known as",
        description:
          "An elevated platform made of rocks, built in the days of Tu'i Tonga empire.",
      },
      {
        name: "ROBERT",
        article: "Someone named",
        description: "This man is programming on a computer.",
      },
    ],
  },
  {
    area: "Wales",
    type: "country",
    neighbors: ["Atlantic Ocean", "England"],
  },
  {
    area: "Western Sahara",
    type: "country",
    neighbors: ["Algeria", "Mauritania", "Morocco"],
  },
  {
    area: "Yemen",
    type: "country",
    neighbors: ["Indian Ocean", "Oman", "Saudi Arabia"],
  },
  {
    area: "Zambia",
    type: "country",
    neighbors: [
      "Angola",
      "Botswana",
      "Democratic Republic of the Congo",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Tanzania",
      "Zimbabwe",
    ],
  },
  {
    area: "Zimbabwe",
    type: "country",
    neighbors: ["Botswana", "Mozambique", "South Africa", "Zambia"],
  },
];
