export const globe = [
  {
    area: "Arctic Ocean",
    type: "ocean",
    neighbors: [
      "Canada",
      "Greenland",
      "Iceland",
      "Norway",
      "Russia",
      "United States",
    ],
  },
  {
    area: "Pacific Ocean",
    type: "ocean",
    neighbors: [
      "Australia",
      "Brunei",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Colombia",
      "Costa Rica",
      "Ecuador",
      "El Salvador",
      "Federated States of Micronesia",
      "Fiji",
      "Guatemala",
      "Honduras",
      "Hong Kong",
      "Indonesia",
      "Japan",
      "Kiribati",
      "Malaysia",
      "Marshall Islands",
      "Mexico",
      "Nauru",
      "New Zealand",
      "Nicaragua",
      "North Korea",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Peru",
      "Philippines",
      "Russia",
      "Samoa",
      "Singapore",
      "Solomon Islands",
      "South Korea",
      "Taiwan",
      "Thailand",
      "East Timor",
      "Tonga",
      "Tuvalu",
      "United States",
      "Vanuatu",
      "Vietnam",
    ],
  },
  {
    area: "Atlantic Ocean",
    type: "ocean",
    neighbors: [
      "Albania",
      "Belgium",
      "Bermuda",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Iceland",
      "Ireland",
      "Italy",
      "Latvia",
      "Lithuania",
      "Malta",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Turkey",
      "Ukraine",
      "Algeria",
      "Angola",
      "Benin",
      "Cameroon",
      "Cape Verde",
      "Democratic Republic of the Congo",
      "Egypt",
      "England",
      "Equatorial Guinea",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Ivory Coast",
      "Liberia",
      "Libya",
      "Mauritania",
      "Morocco",
      "Namibia",
      "Nigeria",
      "Republic of the Congo",
      "São Tomé and Príncipe",
      "Scotland",
      "Senegal",
      "Sierra Leone",
      "South Africa",
      "Togo",
      "Tunisia",
      "Cyprus",
      "Georgia",
      "Israel",
      "Lebanon",
      "Russia",
      "Palestine",
      "Syria",
      "Turkey",
      "Argentina",
      "Brazil",
      "Chile",
      "Colombia",
      "Suriname",
      "Uruguay",
      "Venezuela",
      "Bahamas",
      "Belize",
      "Bermuda",
      "Canada",
      "Costa Rica",
      "Guatemala",
      "Honduras",
      "Mexico",
      "Nicaragua",
      "Panama",
      "United States",
      "Antigua and Barbuda",
      "Guyana",
      "Barbados",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "Grenada",
      "Haiti",
      "Jamaica",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Svalbard",
      "Trinidad and Tobago",
      "Ireland",
    ],
  },
  {
    area: "Indian Ocean",
    type: "ocean",
    neighbors: [
      "Australia",
      "Bahrain",
      "Bangladesh",
      "Comoros",
      "Djibouti",
      "Egypt",
      "Eritrea",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Jordan",
      "Kenya",
      "Kuwait",
      "Madagascar",
      "Malaysia",
      "Maldives",
      "Mauritius",
      "Mozambique",
      "Myanmar",
      "Oman",
      "Pakistan",
      "Qatar",
      "Saudi Arabia",
      "Seychelles",
      "Singapore",
      "Somalia",
      "South Africa",
      "Sri Lanka",
      "Sudan",
      "Tanzania",
      "Thailand",
      "East Timor",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    area: "Abkhazia",
    type: "country",
    neighbors: ["Russia", "Georgia"],
  },
  {
    area: "Afghanistan",
    type: "country",
    neighbors: [
      "China",
      "Iran",
      "Pakistan",
      "Tajikistan",
      "Turkmenistan",
      "Uzbekistan",
    ],
  },
  {
    area: "Albania",
    type: "country",
    neighbors: [
      "Greece",
      "Kosovo",
      "North Macedonia",
      "Montenegro",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Algeria",
    type: "country",
    neighbors: [
      "Libya",
      "Mali",
      "Mauritania",
      "Morocco",
      "Niger",
      "Tunisia",
      "Western Sahara",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Andorra",
    type: "country",
    neighbors: ["France", "Spain"],
  },
  {
    area: "Angola",
    type: "country",
    neighbors: [
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "Namibia",
      "Zambia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Antigua and Barbuda",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Argentina",
    type: "country",
    neighbors: ["Bolivia", "Brazil", "Chile", "Paraguay", "Uruguay"],
  },
  {
    area: "Armenia",
    type: "country",
    neighbors: ["Azerbaijan", "Georgia", "Iran", "Turkey"],
  },
  {
    area: "Australia",
    type: "country",
    neighbors: ["Pacific Ocean", "Indian Ocean"],
  },
  {
    area: "Austria",
    type: "country",
    neighbors: [
      "Czech Republic",
      "Germany",
      "Hungary",
      "Italy",
      "Liechtenstein",
      "Slovakia",
      "Slovenia",
      "Switzerland",
    ],
  },
  {
    area: "Azerbaijan",
    type: "country",
    neighbors: ["Armenia", "Georgia", "Iran", "Russia", "Turkey"],
  },
  {
    area: "Bahamas",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Bahrain",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Bangladesh",
    type: "country",
    neighbors: ["India", "Myanmar", "Indian Ocean"],
  },
  {
    area: "Barbados",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Belarus",
    type: "country",
    neighbors: ["Latvia", "Lithuania", "Poland", "Russia", "Ukraine"],
  },
  {
    area: "Belgium",
    type: "country",
    neighbors: [
      "France",
      "Germany",
      "Luxembourg",
      "Netherlands",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Belize",
    type: "country",
    neighbors: ["Guatemala", "Mexico", "Atlantic Ocean"],
  },
  {
    area: "Benin",
    type: "country",
    neighbors: ["Burkina Faso", "Niger", "Nigeria", "Togo", "Atlantic Ocean"],
  },
  {
    area: "Bermuda",
    type: "special",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Bhutan",
    type: "country",
    neighbors: ["China", "India"],
  },
  {
    area: "Bolivia",
    type: "country",
    neighbors: ["Argentina", "Brazil", "Chile", "Paraguay", "Peru"],
  },
  {
    area: "Bosnia and Herzegovina",
    type: "country",
    neighbors: ["Croatia", "Montenegro", "Serbia", "Atlantic Ocean"],
  },
  {
    area: "Botswana",
    type: "country",
    neighbors: ["Namibia", "South Africa", "Zambia", "Zimbabwe"],
  },
  {
    area: "Brazil",
    type: "country",
    neighbors: [
      "Argentina",
      "Bolivia",
      "Colombia",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Brunei",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Bulgaria",
    type: "country",
    neighbors: [
      "Greece",
      "North Macedonia",
      "Romania",
      "Serbia",
      "Turkey",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Burkina Faso",
    type: "country",
    neighbors: ["Benin", "Côte d'Ivoire", "Ghana", "Mali", "Niger", "Togo"],
  },
  {
    area: "Burundi",
    type: "country",
    neighbors: ["Democratic Republic of the Congo", "Rwanda", "Tanzania"],
  },
  {
    area: "Cambodia",
    type: "country",
    neighbors: ["Laos", "Thailand", "Vietnam", "Pacific Ocean"],
  },
  {
    area: "Cameroon",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Chad",
      "Republic of the Congo",
      "Equatorial Guinea Gabon Nigeria",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Canada",
    type: "country",
    neighbors: [
      "United States",
      "Pacific Ocean",
      "Atlantic Ocean",
      "Arctic Ocean",
    ],
  },
  {
    area: "Cape Verde",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Central African Republic",
    type: "country",
    neighbors: [
      "Cameroon",
      "Chad",
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "South Sudan",
      "Sudan",
    ],
  },
  {
    area: "Chad",
    type: "country",
    neighbors: [
      "Cameroon",
      "Central African Republic",
      "Libya",
      "Niger",
      "Nigeria",
      "Sudan",
    ],
  },
  {
    area: "Chile",
    type: "country",
    neighbors: [
      "Argentina",
      "Bolivia",
      "Peru",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "China",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Bhutan",
      "India",
      "Hong Kong",
      "Kazakhstan",
      "North Korea",
      "Kyrgyzstan",
      "Laos",
      "Macau",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "Pakistan",
      "Russia",
      "Tajikistan",
      "Vietnam",
      "Pacific Ocean",
    ],
  },
  {
    area: "Colombia",
    type: "country",
    neighbors: [
      "Brazil",
      "Ecuador",
      "Panama",
      "Peru",
      "Venezuela",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Comoros",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Democratic Republic of the Congo",
    type: "country",
    neighbors: [
      "Angola",
      "Burundi",
      "Central African Republic",
      "Republic of the Congo",
      "Rwanda",
      "South Sudan",
      "Tanzania",
      "Uganda",
      "Zambia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Republic of the Congo",
    type: "country",
    neighbors: [
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Democratic Republic of the Congo",
      " Gabon",
    ],
  },
  {
    area: "Costa Rica",
    type: "country",
    neighbors: ["Nicaragua", "Panama", "Pacific Ocean", "Atlantic Ocean"],
  },
  {
    area: "Côte d'Ivoire",
    type: "country",
    neighbors: [
      "Burkina Faso",
      "Ghana",
      " Guinea",
      " Liberia",
      "Mali",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Croatia",
    type: "country",
    neighbors: [
      "Bosnia and Herzegovina",
      "Hungary",
      "Montenegro",
      "Serbia",
      "Slovenia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Cuba",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Cyprus",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Czech Republic",
    type: "country",
    neighbors: ["Austria", " Germany", " Poland", " Slovakia"],
  },
  {
    area: "Denmark",
    type: "country",
    neighbors: ["Germany", "Atlantic Ocean"],
  },
  {
    area: "Djibouti",
    type: "country",
    neighbors: ["Eritrea", " Ethiopia", "Somaliland", "Indian Ocean"],
  },
  {
    area: "Dominica",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Dominican Republic",
    type: "country",
    neighbors: ["Haiti", "Atlantic Ocean"],
  },
  {
    area: "East Timor",
    type: "country",
    neighbors: ["Indonesia", "Pacific Ocean", "Indian Ocean"],
  },
  {
    area: "Ecuador",
    type: "country",
    neighbors: ["Colombia", "Peru", "Pacific Ocean"],
  },
  {
    area: "Egypt",
    type: "country",
    neighbors: [
      "Gaza Strip",
      "Israel",
      "Libya",
      "Sudan",
      "Atlantic Ocean",
      "Indian Ocean",
    ],
  },
  {
    area: "El Salvador",
    type: "country",
    neighbors: ["Guatemala", "Honduras", "Pacific Ocean"],
  },
  {
    area: "England",
    type: "country",
    neighbors: ["Scotland", "Wales", "Atlantic Ocean"],
  },
  {
    area: "Equatorial Guinea",
    type: "country",
    neighbors: ["Cameroon", "Gabon", "Atlantic Ocean"],
  },
  {
    area: "Eritrea",
    type: "country",
    neighbors: ["Djibouti", " Ethiopia", " Sudan", "Indian Ocean"],
  },
  {
    area: "Estonia",
    type: "country",
    neighbors: ["Latvia", "Russia", "Atlantic Ocean"],
  },
  {
    area: "Eswatini",
    type: "country",
    neighbors: ["Mozambique", "South Africa"],
  },
  {
    area: "Ethiopia",
    type: "country",
    neighbors: [
      "Djibouti",
      "Eritrea",
      "Kenya",
      "Somalia",
      "South Sudan",
      " Sudan",
    ],
  },
  {
    area: "Fiji",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Finland",
    type: "country",
    neighbors: ["Norway", "Sweden", " Russia", "Atlantic Ocean"],
  },
  {
    area: "France",
    type: "country",
    neighbors: [
      "Andorra",
      "Belgium",
      "Germany",
      "Italy",
      "Luxembourg",
      "Monaco",
      "Spain",
      "Switzerland",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Gabon",
    type: "country",
    neighbors: [
      "Cameroon",
      "Republic of the Congo",
      "Equatorial Guinea",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Gambia",
    type: "country",
    neighbors: ["Senegal", "Atlantic Ocean"],
  },
  {
    area: "Georgia",
    type: "country",
    neighbors: [
      "Armenia",
      "Azerbaijan",
      "Russia",
      "Turkey",
      "Abkhazia",
      "South Ossetia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Germany",
    type: "country",
    neighbors: [
      "Austria",
      "Belgium",
      "Czech Republic",
      "Denmark",
      "France",
      "Luxembourg",
      "Netherlands",
      "Poland",
      "Switzerland",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Ghana",
    type: "country",
    neighbors: ["Burkina Faso", "Côte d'Ivoire", "Togo", "Atlantic Ocean"],
  },
  {
    area: "Greece",
    type: "country",
    neighbors: [
      "Albania",
      "Bulgaria",
      "Turkey",
      "North Macedonia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Greenland",
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean"],
  },
  {
    area: "Grenada",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Guatemala",
    type: "country",
    neighbors: [
      "Belize",
      "El Salvador",
      "Honduras",
      "Mexico",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Guinea",
    type: "country",
    neighbors: [
      "Côte d'Ivoire",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Senegal",
      "Sierra Leone",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Guinea-Bissau",
    type: "country",
    neighbors: ["Guinea", "Senegal", "Atlantic Ocean"],
  },
  {
    area: "Guyana",
    type: "country",
    neighbors: ["Brazil", "Suriname", "Venezuela", "Atlantic Ocean"],
  },
  {
    area: "Haiti",
    type: "country",
    neighbors: ["Dominican Republic", "Atlantic Ocean"],
  },
  {
    area: "Honduras",
    type: "country",
    neighbors: [
      "Guatemala",
      "El Salvador",
      "Nicaragua",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Hong Kong",
    type: "special",
    neighbors: ["China", "Pacific Ocean"],
  },
  {
    area: "Hungary",
    type: "country",
    neighbors: [
      "Austria",
      "Croatia",
      "Romania",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Ukraine",
    ],
  },
  {
    area: "Iceland",
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean"],
  },
  {
    area: "India",
    type: "country",
    neighbors: [
      "Bangladesh",
      " Bhutan",
      " China",
      " Myanmar",
      " Nepal",
      " Pakistan",
      "Sri Lanka",
      "Indian Ocean",
    ],
  },
  {
    area: "Indonesia",
    type: "country",
    neighbors: [
      "East Timor",
      "Malaysia",
      "Papua New Guinea",
      "Pacific Ocean",
      "Indian Ocean",
    ],
  },
  {
    area: "Iran",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Armenia",
      " Azerbaijan",
      "Iraq",
      "Pakistan",
      "Turkey",
      "Turkmenistan",
      "Indian Ocean",
    ],
  },
  {
    area: "Iraq",
    type: "country",
    neighbors: [
      "Iran",
      "Jordan",
      "Kuwait",
      "Saudi Arabia",
      "Syria",
      "Turkey",
      "Indian Ocean",
    ],
  },
  {
    area: "Ireland",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Israel",
    type: "country",
    neighbors: [
      "Egypt",
      "Jordan",
      "Lebanon",
      "Syria",
      "Atlantic Ocean",
      "Indian Ocean",
    ],
  },
  {
    area: "Italy",
    type: "country",
    neighbors: [
      "Austria",
      "France",
      "San Marino",
      "Slovenia",
      "Switzerland",
      "Vatican City",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Jamaica",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Japan",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Jordan",
    type: "country",
    neighbors: ["Iraq", "Israel", "Saudi Arabia", "Syria", "Indian Ocean"],
  },
  {
    area: "Kazakhstan",
    type: "country",
    neighbors: ["China", " Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
  },
  {
    area: "Kenya",
    type: "country",
    neighbors: [
      "Ethiopia",
      "Somalia",
      "South Sudan",
      "Tanzania",
      "Uganda",
      "Indian Ocean",
    ],
  },
  {
    area: "Kiribati",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "North Korea",
    type: "country",
    neighbors: ["China", "South Korea", "Russia", "Pacific Ocean"],
  },
  {
    area: "South Korea",
    type: "country",
    neighbors: ["North Korea", "Pacific Ocean"],
  },
  {
    area: "Kosovo",
    type: "country",
    neighbors: ["Albania", "Montenegro", "North Macedonia", "Serbia"],
  },
  {
    area: "Kuwait",
    type: "country",
    neighbors: ["Iraq", "Saudi Arabia", "Indian Ocean"],
  },
  {
    area: "Kyrgyzstan",
    type: "country",
    neighbors: ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
  },
  {
    area: "Laos",
    type: "country",
    neighbors: ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
  },
  {
    area: "Latvia",
    type: "country",
    neighbors: ["Belarus", "Estonia", "Lithuania", "Russia", "Atlantic Ocean"],
  },
  {
    area: "Lebanon",
    type: "country",
    neighbors: ["Israel", "Syria", "Atlantic Ocean"],
  },
  {
    area: "Lesotho",
    type: "country",
    neighbors: ["South Africa"],
  },
  {
    area: "Liberia",
    type: "country",
    neighbors: ["Guinea", "Côte d'Ivoire", "Sierra Leone", "Atlantic Ocean"],
  },
  {
    area: "Libya",
    type: "country",
    neighbors: [
      "Algeria",
      "Chad",
      "Egypt",
      "Niger",
      "Sudan",
      "Tunisia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Liechtenstein",
    type: "country",
    neighbors: ["Austria", "Switzerland"],
  },
  {
    area: "Lithuania",
    type: "country",
    neighbors: ["Belarus", "Latvia", "Poland", "Russia", "Atlantic Ocean"],
  },
  {
    area: "Luxembourg",
    type: "country",
    neighbors: ["Belgium", "France", "Germany"],
  },
  {
    area: "Macau",
    type: "country",
    neighbors: ["China", "Pacific Ocean"],
  },
  {
    area: "Madagascar",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Madeira",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Malawi",
    type: "country",
    neighbors: ["Mozambique", "Tanzania", "Zambia"],
  },
  {
    area: "Malaysia",
    type: "country",
    neighbors: [
      "Brunei",
      "Indonesia",
      "Thailand",
      "Pacific Ocean",
      "Indian Ocean",
    ],
  },
  {
    area: "Maldives",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Mali",
    type: "country",
    neighbors: [
      "Algeria",
      "Burkina Faso",
      "Côte d'Ivoire",
      "Guinea",
      "Mauritania",
      "Niger",
      "Senegal",
    ],
  },
  {
    area: "Malta",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Marshall Islands",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Mauritania",
    type: "country",
    neighbors: [
      "Algeria",
      "Mali",
      "Senegal",
      "Western Sahara",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Mauritius",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Mexico",
    type: "country",
    neighbors: [
      "Belize",
      "Guatemala",
      "United States",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Federated States of Micronesia",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Moldova",
    type: "country",
    neighbors: ["Romania", "Ukraine"],
  },
  {
    area: "Monaco",
    type: "country",
    neighbors: ["France", "Atlantic Ocean"],
  },
  {
    area: "Mongolia",
    type: "country",
    neighbors: ["China", "Russia"],
  },
  {
    area: "Montenegro",
    type: "country",
    neighbors: [
      "Albania",
      "Bosnia and Herzegovina",
      "Croatia",
      "Kosovo",
      "Serbia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Morocco",
    type: "country",
    neighbors: ["Algeria", "Western Sahara", "Spain", "Atlantic Ocean"],
  },
  {
    area: "Mozambique",
    type: "country",
    neighbors: [
      "Eswatini",
      "Malawi",
      "South Africa",
      "Tanzania",
      "Zambia",
      "Zimbabwe",
      "Indian Ocean",
    ],
  },
  {
    area: "Myanmar",
    type: "country",
    neighbors: [
      "Bangladesh",
      "China",
      "India",
      "Laos",
      "Thailand",
      "Indian Ocean",
    ],
  },
  {
    area: "Namibia",
    type: "country",
    neighbors: [
      "Angola",
      "Botswana",
      "South Africa",
      "Zambia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Nauru",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Nepal",
    type: "country",
    neighbors: ["China", "India"],
  },
  {
    area: "Netherlands",
    type: "country",
    neighbors: [
      "Belgium",
      "Germany",
      "Saint Martin",
      "France",
      "Atlantic Ocean",
    ],
  },
  {
    area: "New Zealand",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Nicaragua",
    type: "country",
    neighbors: ["Costa Rica", "Honduras", "Pacific Ocean", "Atlantic Ocean"],
  },
  {
    area: "Niger",
    type: "country",
    neighbors: [
      "Algeria",
      "Benin",
      "Burkina Faso",
      "Chad",
      "Libya",
      "Mali",
      "Nigeria",
    ],
  },
  {
    area: "Nigeria",
    type: "country",
    neighbors: ["Benin", "Cameroon", "Chad", "Niger", "Atlantic Ocean"],
  },
  {
    area: "North Macedonia",
    type: "country",
    neighbors: ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
  },
  {
    area: "Norway",
    type: "country",
    neighbors: [
      "Finland",
      "Sweden",
      "Russia",
      "Arctic Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Oman",
    type: "country",
    neighbors: [
      "Saudi Arabia",
      "United Arab Emirates",
      "Yemen",
      "Indian Ocean",
    ],
  },
  {
    area: "Pakistan",
    type: "country",
    neighbors: ["Afghanistan", "India", "Iran", "China", "Indian Ocean"],
  },
  {
    area: "Palau",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Palestine",
    type: "country",
    neighbors: ["Egypt", "Israel", "Jordan", "Atlantic Ocean"],
  },
  {
    area: "Panama",
    type: "country",
    neighbors: ["Colombia", "Costa Rica", "Pacific Ocean", "Atlantic Ocean"],
  },
  {
    area: "Papua New Guinea",
    type: "country",
    neighbors: ["Indonesia", "Pacific Ocean"],
  },
  {
    area: "Paraguay",
    type: "country",
    neighbors: ["Argentina", "Bolivia", "Brazil"],
  },
  {
    area: "Peru",
    type: "country",
    neighbors: [
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Pacific Ocean",
    ],
  },
  {
    area: "Philippines",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Poland",
    type: "country",
    neighbors: [
      "Belarus",
      "Czech Republic",
      "Germany",
      "Lithuania",
      "Russia",
      "Slovakia",
      "Ukraine",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Portugal",
    type: "country",
    neighbors: ["Spain", "Atlantic Ocean"],
  },
  {
    area: "Qatar",
    type: "country",
    neighbors: ["Saudi Arabia", "Indian Ocean"],
  },
  {
    area: "Romania",
    type: "country",
    neighbors: [
      "Bulgaria",
      "Hungary",
      "Moldova",
      "Serbia",
      "Ukraine",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Russia",
    type: "country",
    neighbors: [
      "Azerbaijan",
      "Belarus",
      "China",
      "Estonia",
      "Finland",
      "Georgia",
      "Kazakhstan",
      "North Korea",
      "Latvia",
      "Lithuania",
      "Mongolia",
      "Norway",
      "Poland",
      "Ukraine",
      "South Ossetia",
      "Abkhazia",
      "Arctic Ocean",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Rwanda",
    type: "country",
    neighbors: [
      "Burundi",
      "Democratic Republic of the Congo",
      "Tanzania",
      "Uganda",
    ],
  },
  {
    area: "Saint Kitts and Nevis",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saint Lucia",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saint Vincent and the Grenadines",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Samoa",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "San Marino",
    type: "country",
    neighbors: ["Italy"],
  },
  {
    area: "São Tomé and Príncipe",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saudi Arabia",
    type: "country",
    neighbors: [
      "Iraq",
      "Jordan",
      "Kuwait",
      "Oman",
      "Qatar",
      "United Arab Emirates",
      "Yemen",
      "Indian Ocean",
    ],
  },
  {
    area: "Scotland",
    type: "country",
    neighbors: ["England", "Atlantic Ocean"],
  },
  {
    area: "Senegal",
    type: "country",
    neighbors: [
      "Gambia",
      "Guinea",
      "Guinea-Bissau",
      "Mali",
      "Mauritania",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Serbia",
    type: "country",
    neighbors: [
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Hungary",
      "Kosovo",
      "Montenegro",
      "North Macedonia",
      "Romania",
    ],
  },
  {
    area: "Seychelles",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Sierra Leone",
    type: "country",
    neighbors: ["Guinea", "Liberia", "Atlantic Ocean"],
  },
  {
    area: "Singapore",
    type: "country",
    neighbors: ["Pacific Ocean", "Indian Ocean"],
  },
  {
    area: "Slovakia",
    type: "country",
    neighbors: ["Austria", "Czech Republic", "Hungary", "Poland", "Ukraine"],
  },
  {
    area: "Slovenia",
    type: "country",
    neighbors: ["Austria", "Croatia", "Italy", "Hungary", "Atlantic Ocean"],
  },
  {
    area: "Solomon Islands",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Somalia",
    type: "country",
    neighbors: ["Djibouti", "Ethiopia", "Kenya", "Indian Ocean"],
  },
  {
    area: "South Africa",
    type: "country",
    neighbors: [
      "Botswana",
      "Eswatini",
      "Lesotho",
      "Mozambique",
      "Namibia",
      "Zimbabwe",
      "Atlantic Ocean",
      "Indian Ocean",
    ],
  },
  {
    area: "South Ossetia",
    type: "country",
    neighbors: ["Russia", "Georgia"],
  },
  {
    area: "South Sudan",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Democratic Republic of the Congo",
      "Ethiopia",
      "Kenya",
      "Sudan",
      "Uganda",
    ],
  },
  {
    area: "Spain",
    type: "country",
    neighbors: [
      "Andorra",
      "France",
      "Portugal",
      "Gibraltar",
      "Morocco",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Sri Lanka",
    type: "country",
    neighbors: ["India", "Indian Ocean"],
  },
  {
    area: "Sudan",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Chad",
      "Egypt",
      "Eritrea",
      "Ethiopia",
      "Libya",
      "South Sudan",
      "Indian Ocean",
    ],
  },
  {
    area: "Suriname",
    type: "country",
    neighbors: ["Brazil", "French Guiana", "Guyana", "Atlantic Ocean"],
  },
  {
    area: "Svalbard",
    type: "special",
    neighbors: ["Brazil", "French Guiana", "Guyana", "Atlantic Ocean"],
  },
  {
    area: "Sweden",
    type: "country",
    neighbors: ["Finland", "Norway", "Atlantic Ocean"],
  },
  {
    area: "Switzerland",
    type: "country",
    neighbors: ["Austria", "France", "Italy", "Liechtenstein", "Germany"],
  },
  {
    area: "Syria",
    type: "country",
    neighbors: [
      "Iraq",
      "Israel",
      "Jordan",
      "Lebanon",
      "Turkey",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Taiwan",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Tajikistan",
    type: "country",
    neighbors: ["Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"],
  },
  {
    area: "Tanzania",
    type: "country",
    neighbors: [
      "Burundi",
      "Democratic Republic of the Congo",
      "Kenya",
      "Malawi",
      "Mozambique",
      "Rwanda",
      "Uganda",
      "Zambia",
      "Indian Ocean",
    ],
  },
  {
    area: "Tasmania",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Thailand",
    type: "country",
    neighbors: [
      "Cambodia",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Pacific Ocean",
      "Indian Ocean",
    ],
  },
  {
    area: "Togo",
    type: "country",
    neighbors: ["Benin", "Burkina Faso", "Ghana"],
  },
  {
    area: "Tonga",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Trinidad and Tobago",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Tunisia",
    type: "country",
    neighbors: ["Algeria", "Libya"],
  },
  {
    area: "Turkey",
    type: "country",
    neighbors: [
      "Armenia",
      "Azerbaijan",
      "Bulgaria",
      "Georgia",
      "Greece",
      "Iran",
      "Iraq",
      "Syria",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Turkmenistan",
    type: "country",
    neighbors: ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan"],
  },
  {
    area: "Tuvalu",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Uganda",
    type: "country",
    neighbors: [
      "Democratic Republic of the Congo",
      "Kenya",
      "Rwanda",
      "South Sudan",
      "Tanzania",
    ],
  },
  {
    area: "Ukraine",
    type: "country",
    neighbors: [
      "Belarus",
      "Hungary",
      "Moldova",
      "Poland",
      "Romania",
      "Russia",
      "Slovakia",
    ],
  },
  {
    area: "United Arab Emirates",
    type: "country",
    neighbors: ["Oman", "Saudi Arabia", "Indian Ocean"],
  },
  {
    area: "United States",
    type: "country",
    neighbors: [
      "Canada",
      "Mexico",
      "Arctic Ocean",
      "Pacific Ocean",
      "Atlantic Ocean",
    ],
    objects: ["The Brooklyn Bridge"],
  },
  {
    area: "Uruguay",
    type: "country",
    neighbors: ["Argentina", "Brazil", "Atlantic Ocean"],
  },
  {
    area: "Uzbekistan",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Kazakhstan",
      "Kyrgyzstan",
      "Tajikistan",
      "Turkmenistan",
    ],
  },
  {
    area: "Vanuatu",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Vatican City",
    type: "country",
    neighbors: ["Italy"],
  },
  {
    area: "Venezuela",
    type: "country",
    neighbors: ["Brazil", "Colombia", "Guyana", "Atlantic Ocean"],
  },
  {
    area: "Vietnam",
    type: "country",
    neighbors: ["Cambodia", "China", "Laos", "Pacific Ocean"],
  },
  {
    area: "Wales",
    type: "country",
    neighbors: ["England", "Atlantic Ocean"],
  },
  {
    area: "Western Sahara",
    type: "country",
    neighbors: ["Algeria", "Mauritania", "Morocco"],
  },
  {
    area: "Yemen",
    type: "country",
    neighbors: ["Oman", "Saudi Arabia", "Indian Ocean"],
  },
  {
    area: "Zambia",
    type: "country",
    neighbors: [
      "Angola",
      "Botswana",
      "Democratic Republic of the Congo",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Tanzania",
      "Zimbabwe",
    ],
  },
  {
    area: "Zimbabwe",
    type: "country",
    neighbors: ["Botswana", "Mozambique", "South Africa", "Zambia"],
  },
];
