export let globe = [
  {
    area: "Arctic Ocean",
    type: "ocean",
    objects: [
      {
        name: "NORTH POLE FLAG",
        article: "The",
        description:
          "A Russian flag on the sea floor is the only permanent marker of the planet's geographic north pole.",
      },
      {
        name: "LOST PENGUIN",
        article: "A",
        description:
          "A funny-looking flightless bird. This one explains that he normally lives at the south pole, but nothing is stopping him from traveling.",
      },
      {
        name: "PETROLEUM",
        article: "Some",
        description: "A viscous, yellowish-black liquid used to power chainsaws.",
      },
    ],
    neighbors: [
      "Atlantic Ocean",
      "Pacific Ocean",
      "Canada",
      "Greenland",
      "Iceland",
      "Norway",
      "Russia",
      "United States",
    ],
  },
  {
    area: "Pacific Ocean",
    type: "ocean",
    description:
      "The Pacific Ocean was first discovered by single-celled organisms billions of years ago, but it wasn't explored until much later, by fish.",
    objects: [
      {
        name: "WATER",
        description: "A pile of water, currently in liquid form",
        article: "A lot of",
      },
    ],
    neighbors: [
      "Atlantic Ocean",
      "Arctic Ocean",
      "Australia",
      "Brunei",
      "Cambodia",
      "Canada",
      "Chile",
      "China",
      "Colombia",
      "Costa Rica",
      "East Timor",
      "Easter Island",
      "Ecuador",
      "El Salvador",
      "Federated States of Micronesia",
      "Fiji",
      "Guatemala",
      "Honduras",
      "Hong Kong",
      "Indonesia",
      "Japan",
      "Kiribati",
      "Malaysia",
      "Marshall Islands",
      "Mexico",
      "Nauru",
      "New Zealand",
      "Nicaragua",
      "North Korea",
      "Palau",
      "Panama",
      "Papua New Guinea",
      "Peru",
      "Philippines",
      "Russia",
      "Samoa",
      "Singapore",
      "Solomon Islands",
      "South Korea",
      "Taiwan",
      "Thailand",
      "Tonga",
      "Tuvalu",
      "United States",
      "Vanuatu",
      "Vietnam",
      "Wallis Island",
    ],
  },
  {
    area: "Atlantic Ocean",
    description:
      "Considered by many to be the one of hte best oceans on the planet, you're glad you found time to see it up close.",
    type: "ocean",
    neighbors: [
      "Albania",
      "Algeria",
      "Angola",
      "Antigua and Barbuda",
      "Arctic Ocean",
      "Argentina",
      "Bahamas",
      "Barbados",
      "Belgium",
      "Belize",
      "Benin",
      "Bermuda",
      "Bosnia and Herzegovina",
      "Brazil",
      "Bulgaria",
      "Cameroon",
      "Canada",
      "Cape Verde",
      "Chile",
      "Colombia",
      "Costa Rica",
      "Croatia",
      "Cuba",
      "Cyprus",
      "Cyprus",
      "Democratic Republic of the Congo",
      "Denmark",
      "Dominica",
      "Dominican Republic",
      "Egypt",
      "England",
      "Equatorial Guinea",
      "Estonia",
      "Finland",
      "France",
      "Gabon",
      "Gambia",
      "Georgia",
      "Georgia",
      "Germany",
      "Ghana",
      "Greece",
      "Grenada",
      "Guatemala",
      "Guinea-Bissau",
      "Guinea",
      "Guyana",
      "Haiti",
      "Honduras",
      "Iceland",
      "Ireland",
      "Ireland",
      "Israel",
      "Italy",
      "Ivory Coast",
      "Jamaica",
      "Latvia",
      "Lebanon",
      "Liberia",
      "Libya",
      "Lithuania",
      "Malta",
      "Mauritania",
      "Mexico",
      "Monaco",
      "Montenegro",
      "Morocco",
      "Namibia",
      "Netherlands",
      "Nicaragua",
      "Nigeria",
      "Norway",
      "Pacific Ocean",
      "Palestine",
      "Panama",
      "Poland",
      "Portugal",
      "Republic of the Congo",
      "Romania",
      "Russia",
      "Russia",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "São Tomé and Príncipe",
      "Scotland",
      "Senegal",
      "Sierra Leone",
      "Slovenia",
      "South Africa",
      "Spain",
      "Suriname",
      "Svalbard",
      "Sweden",
      "Syria",
      "Togo",
      "Trinidad and Tobago",
      "Tunisia",
      "Turkey",
      "Turkey",
      "Ukraine",
      "United States",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    area: "Indian Ocean",
    description: "This ocean hosts the largest phytoplankton blooms, bar none.",
    objects: [
      {
        name: "PHYTOPLANKTON BLOOM",
        article: "A",
        description: "Just look at it! Beautiful.",
      },
    ],
    type: "ocean",
    neighbors: [
      "Australia",
      "Bahrain",
      "Bangladesh",
      "Comoros",
      "Djibouti",
      "East Timor",
      "Egypt",
      "Eritrea",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Jordan",
      "Kenya",
      "Kuwait",
      "Madagascar",
      "Malaysia",
      "Maldives",
      "Mauritius",
      "Mozambique",
      "Myanmar",
      "Oman",
      "Pakistan",
      "Qatar",
      "Saudi Arabia",
      "Seychelles",
      "Singapore",
      "Somalia",
      "South Africa",
      "Sri Lanka",
      "Sudan",
      "Tanzania",
      "Thailand",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    area: "Abkhazia",
    type: "country",
    neighbors: ["Russia", "Georgia"],
  },
  {
    area: "Afghanistan",
    type: "country",
    neighbors: ["China", "Iran", "Pakistan", "Tajikistan", "Turkmenistan", "Uzbekistan"],
  },
  {
    area: "Albania",
    type: "country",
    neighbors: ["Greece", "Kosovo", "North Macedonia", "Montenegro", "Atlantic Ocean"],
  },
  {
    area: "Algeria",
    type: "country",
    description:
      "Looking over the country, you note that about 4/5ths of it is covered by a yellow area called the Sahara Desert, wherein you can spot a FENNEC chasing a beetle along the ridge of a sand dune.",
    objects: [
      {
        name: "FENNEC",
        article: "A",
        description: "A furry little fox with big pointy ears.",
      },
    ],
    neighbors: [
      "Libya",
      "Mali",
      "Mauritania",
      "Morocco",
      "Niger",
      "Tunisia",
      "Western Sahara",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Andorra",
    type: "country",
    neighbors: ["France", "Spain"],
  },
  {
    area: "Angola",
    type: "country",
    neighbors: [
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "Namibia",
      "Zambia",
      "Atlantic Ocean",
    ],
  },
  {
    area: "Antigua and Barbuda",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Argentina",
    type: "country",
    neighbors: ["Bolivia", "Brazil", "Chile", "Library of Babel", "Paraguay", "Uruguay"],
  },
  {
    area: "Armenia",
    type: "country",
    neighbors: ["Azerbaijan", "Georgia", "Iran", "Turkey"],
  },
  {
    area: "Australia",
    type: "country",
    neighbors: ["Pacific Ocean", "Indian Ocean"],
  },
  {
    area: "Austria",
    description:
      "A mountainous nation. Looking around for an ocean to swim in, you notice this country is completely landlocked. You put away your swimsuit and snorkel for another day.",
    objects: [
      {
        name: "UPPER BELVEDERE PALACE",
        article: "The",
        description:
          "A Baroque palace built in the 18th century by Prince Eugene (a lot of the construction work was done by other people though). A massive edifice of white stone, set amidst immaculate lawsns and gardens. Nearby is the Lower Belvedere palace, constructed a few decades previous: it's shit. Not worth mentioning to be honest.",
      },
      {
        name: "MOZART'S PIANO",
        article: "",
        description: "A pretty nice piano. You plink one of the keys: still works!",
      },
      {
        name: "ARNOLD SCHWARZENEGGER",
        article: "",
        description:
          "An elderly man. At the moment, he is pumping iron. You ask him how much he can bench press: '400 kilograms', he says. That sounds like a lot. Is he telling the truth?",
      },
      {
        name: "KURT GÖDEL'S PROOF OF A WEAKNESS IN THE U.S. CONSTITUTION",
        article: "",
        description:
          "Scarcely half a page of hastily-scrawled notes, outlining a method by which the U.S.A. could legally become a dictatorship. Gödel came up with it while studying the constitution prior to taking his citizenship test. You take a moment to read it, and see that it would be very easy to implement, yet impossible to prevent. However, moments later, you've forgotten what it says.",
      },
    ],
    type: "country",
    neighbors: [
      "Czech Republic",
      "Germany",
      "Hungary",
      "Italy",
      "Liechtenstein",
      "Slovakia",
      "Slovenia",
      "Switzerland",
    ],
  },
  {
    area: "Azerbaijan",
    type: "country",
    neighbors: ["Armenia", "Georgia", "Iran", "Russia", "Turkey"],
  },
  {
    area: "Bahamas",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Bahrain",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Bangladesh",
    type: "country",
    neighbors: ["India", "Myanmar", "Indian Ocean"],
  },
  {
    area: "Barbados",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Belarus",
    description:
      "This jewel of the former Soviet Union has 11,000 lakes (suck it, Minnesota!) and their main export is tractors. Unfortunately positioned in the path of larger powers, the armies of Europe have stomped through Belarus for thousands of years, and a change in the weather patterns in April, 1986 meant that most of the radioactive fallout from Chernobyl landed here, instead of in Ukraine. Yet, despite it all, the people remain ever unvanquished, and nature has somewhat made up for their troubled history by gifting this beautiful country with an abundance of peat, granite, sand, and gravel.",
    objects: [
      {
        name: "IRRADIATED FARMLAND",
        article: "Hundreds of miles of",
        description:
          "One-fifth of the land in Belarus is irradiated: mostly forests and farmland. Walking through this area, you see abandoned villages, scattered homesteads, and packs of wild dogs.",
      },
      {
        name: "DRANIKI",
        article: "A warm plate of",
        description:
          "A potato pancake, beloved by the Belarusian people. You take a bite out of one: a little bland. Then, you realize you're supposed to dip it in sour cream. What a difference that makes! Mmm, these draniki are delicious.",
      },
    ],
    type: "country",
    neighbors: ["Latvia", "Lithuania", "Poland", "Russia", "Ukraine"],
  },
  {
    area: "Belgium",
    type: "country",
    neighbors: ["Atlantic Ocean", "France", "Germany", "Luxembourg", "Netherlands"],
  },
  {
    area: "Belize",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guatemala", "Mexico"],
  },
  {
    area: "Benin",
    type: "country",
    neighbors: ["Atlantic Ocean", "Burkina Faso", "Niger", "Nigeria", "Togo"],
  },
  {
    area: "Bermuda",
    type: "special",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Bhutan",
    type: "country",
    neighbors: ["China", "India"],
  },
  {
    area: "Bolivia",
    type: "country",
    neighbors: ["Argentina", "Brazil", "Chile", "Paraguay", "Peru"],
  },
  {
    area: "Bosnia and Herzegovina",
    type: "country",
    neighbors: ["Atlantic Ocean", "Croatia", "Montenegro", "Serbia"],
  },
  {
    area: "Botswana",
    type: "country",
    neighbors: ["Namibia", "South Africa", "Zambia", "Zimbabwe"],
  },
  {
    area: "Brazil",
    type: "country",
    description:
      "You see a country with mountains, and a large swath of equatorial rainforest jungle, containing many animals and plants. You notice a complex system of rivers, with eight separate drainage basins (wow!). The capitol is Brasilia.",
    objects: [
      {
        name: "COFFEA",
        article: "Some",
        description:
          "While surveying the country of Brazil, you spot a shrub with white flowers, bearing clusters of bright, red berries. Looking closer, you notice tens of thousands of people picking, processing, drying, roasting, grinding, brewing, and drinking these berries. When you stop one of them to ask what's going on, he kindly tells you that the COFFEA plant produces coffee, one of the most popular beverages in the world, and that no country produces more coffee than Brazil itself!",
      },
      {
        name: "AMAZON RIVER",
        article: "The",
        description:
          "A long, winding river, teeming with fish. Dipping your toe into it, you are immediately attacked by small, carnivorous fish known as pirahnas. Ouch!",
      },
      {
        name: "CHRIST THE REDEEMER STATUE",
        article: "The",
        description:
          "This huge statue sits atop a mountain overlooking the city of Rio de Janeiro. You would estimate that it is 98 feet tall, and weighs 635 metric tons. If you had to guess, you would say it was built between 1922 and 1931. The statue stands in a T-pose: straight, looking forward, with its arms outstretched, indicating that no animation has been attached to it, or that the existing animations cannot be loaded.",
      },
    ],
    neighbors: [
      "Argentina",
      "Atlantic Ocean",
      "Bolivia",
      "Colombia",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    area: "Brunei",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Bulgaria",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Greece",
      "North Macedonia",
      "Romania",
      "Serbia",
      "Turkey",
    ],
  },
  {
    area: "Burkina Faso",
    type: "country",
    neighbors: ["Benin", "Côte d'Ivoire", "Ghana", "Mali", "Niger", "Togo"],
  },
  {
    area: "Burundi",
    type: "country",
    neighbors: ["Democratic Republic of the Congo", "Rwanda", "Tanzania"],
  },
  {
    area: "Cambodia",
    type: "country",
    neighbors: ["Laos", "Pacific Ocean", "Thailand", "Vietnam"],
  },
  {
    area: "Cameroon",
    description:
      "A country with beaches, deserts, mountains, rainforests, and savannas! From mighty Mount Cameroon in the south, to Lake Chad in the west, and the fascinating volcanic formations in the north, to the massive corruption and human rights abuses in cities like Yaoundé and Douala, Cameroon has something for everybody.",
    type: "country",
    objects: [
      {
        name: "NUTSHELLS",
        article: "A pile of",
        description: "Used in a local gambling game called Abbia.",
      },
      {
        name: "AFO-A-KOM",
        article: "",
        description:
          "A wooden statue of a king on a throne supported by buffalo heads. An sacred object of veneration to the Kom people, it was stolen from its sacred grove in 1966. Fortunately it is magic, and the thieves hands withered and fell off, and the statue was returned to Laikom palace in northern Cameroon, where it remains today, throbbing with terrifying power.",
      },
    ],
    neighbors: [
      "Atlantic Ocean",
      "Central African Republic",
      "Chad",
      "Equatorial Guinea",
      "Gabon",
      "Nigeria",
      "Republic of the Congo",
    ],
  },
  {
    area: "Canada",
    description:
      "A massive country, covered in endless marches of snow. At first, it seems sparsely populated, but as you scan the coastlines, you notice sizable clusters of gentle, industrious citizens (known as 'canadians' or 'canucks') living at the eastern and western edges of the continent.",
    type: "country",
    objects: [
      {
        name: "ZINC",
        article: "Some",
        description:
          "A lump of silver metal. Also known as philosopher's wool, it is useful for weather-proofing everything from fences to noses. When alloyed with copper, it can be used to make trumpets.",
      },
      {
        name: "MAPLE SYRUP",
        article: "Some",
        description:
          "Thick, sweet, and golden in color, MAPLE SYRUP is the national drink of Canada. Canadians consume more of it than any other country in the world — over 160 pounds per person annually, on average. It's a delicious companion on pancakes, flapjacks, and bannock, but it also has medical uses, and is an ingredient in the popular cocktail known as the Mackenzie.",
      },
    ],
    neighbors: ["Arctic Ocean", "Atlantic Ocean", "Pacific Ocean", "United States"],
  },
  {
    area: "Cape Verde",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Central African Republic",
    type: "country",
    neighbors: [
      "Cameroon",
      "Chad",
      "Democratic Republic of the Congo",
      "Republic of the Congo",
      "South Sudan",
      "Sudan",
    ],
  },
  {
    area: "Chad",
    type: "country",
    neighbors: [
      "Cameroon",
      "Central African Republic",
      "Libya",
      "Niger",
      "Nigeria",
      "Sudan",
    ],
  },
  {
    area: "Chile",
    type: "country",
    neighbors: ["Argentina", "Atlantic Ocean", "Bolivia", "Pacific Ocean", "Peru"],
  },
  {
    area: "China",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Bhutan",
      "Hong Kong",
      "India",
      "Kazakhstan",
      "Kyrgyzstan",
      "Laos",
      "Macau",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "North Korea",
      "Pacific Ocean",
      "Pakistan",
      "Russia",
      "Tajikistan",
      "Vietnam",
    ],
  },
  {
    area: "Colombia",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Brazil",
      "Ecuador",
      "Pacific Ocean",
      "Panama",
      "Peru",
      "Venezuela",
    ],
  },
  {
    area: "Comoros",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Democratic Republic of the Congo",
    type: "country",
    neighbors: [
      "Angola",
      "Atlantic Ocean",
      "Burundi",
      "Central African Republic",
      "Republic of the Congo",
      "Rwanda",
      "South Sudan",
      "Tanzania",
      "Uganda",
      "Zambia",
    ],
  },
  {
    area: "Republic of the Congo",
    type: "country",
    neighbors: [
      "Angola",
      "Cameroon",
      "Central African Republic",
      "Democratic Republic of the Congo",
      "Gabon",
    ],
  },
  {
    area: "Costa Rica",
    type: "country",
    neighbors: ["Atlantic Ocean", "Nicaragua", "Pacific Ocean", "Panama"],
  },
  {
    area: "Côte d'Ivoire",
    type: "country",
    neighbors: ["Atlantic Ocean", "Burkina Faso", "Ghana", "Guinea", "Liberia", "Mali"],
  },
  {
    area: "Croatia",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Bosnia and Herzegovina",
      "Hungary",
      "Montenegro",
      "Serbia",
      "Slovenia",
    ],
  },
  {
    area: "Cuba",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Cyprus",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Czech Republic",
    type: "country",
    neighbors: ["Austria", " Germany", "Poland", " Slovakia"],
  },
  {
    area: "Denmark",
    type: "country",
    neighbors: ["Germany", "Atlantic Ocean"],
  },
  {
    area: "Djibouti",
    type: "country",
    neighbors: ["Eritrea", "Ethiopia", "Indian Ocean", "Somaliland"],
  },
  {
    area: "Dominica",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Dominican Republic",
    type: "country",
    neighbors: ["Atlantic Ocean", "Haiti"],
  },
  {
    area: "Easter Island",
    type: "special",
    neighbors: ["Pacific Ocean"],
    objects: [
      {
        name: "MOAI STATUE",
        article: "A",
        description: "A massive stone monolith in the shape of a person.",
      },
      {
        name: "SIROLIMUS",
        article: "A vial of",
        description:
          "This immunosuppressant drug is used to prevent organ transplant rejection. As everybody already knows, sirolimus was discovered on Easter Island, in a soil sample containing streptomyces hygroscopicus.",
      },
    ],
  },
  {
    area: "East Timor",
    type: "country",
    neighbors: ["Indonesia", "Indian Ocean", "Pacific Ocean"],
  },
  {
    area: "Ecuador",
    type: "country",
    neighbors: ["Colombia", "Pacific Ocean", "Peru"],
  },
  {
    area: "Egypt",
    type: "country",
    neighbors: ["Atlantic Ocean", "Indian Ocean", "Israel", "Libya", "Sudan"],
  },
  {
    area: "El Salvador",
    type: "country",
    neighbors: ["Guatemala", "Honduras", "Pacific Ocean"],
  },
  {
    area: "England",
    type: "country",
    neighbors: ["Atlantic Ocean", "Scotland", "Wales"],
  },
  {
    area: "Equatorial Guinea",
    type: "country",
    neighbors: ["Atlantic Ocean", "Cameroon", "Gabon"],
  },
  {
    area: "Eritrea",
    type: "country",
    neighbors: ["Djibouti", "Ethiopia", "Indian Ocean", "Sudan"],
  },
  {
    area: "Estonia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Latvia", "Russia"],
  },
  {
    area: "Eswatini",
    type: "country",
    neighbors: ["Mozambique", "South Africa"],
  },
  {
    area: "Ethiopia",
    type: "country",
    neighbors: ["Djibouti", "Eritrea", "Kenya", "Somalia", "South Sudan", "Sudan"],
  },
  {
    area: "Fiji",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Finland",
    type: "country",
    neighbors: ["Atlantic Ocean", "Norway", "Sweden", "Russia"],
  },
  {
    area: "France",
    type: "country",
    neighbors: [
      "Andorra",
      "Atlantic Ocean",
      "Belgium",
      "Germany",
      "Italy",
      "Luxembourg",
      "Monaco",
      "Spain",
      "Switzerland",
    ],
  },
  {
    area: "Gabon",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Cameroon",
      "Equatorial Guinea",
      "Republic of the Congo",
    ],
  },
  {
    area: "Gambia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Senegal"],
  },
  {
    area: "Georgia",
    type: "country",
    neighbors: [
      "Abkhazia",
      "Armenia",
      "Atlantic Ocean",
      "Azerbaijan",
      "Russia",
      "South Ossetia",
      "Turkey",
    ],
  },
  {
    area: "Germany",
    type: "country",
    description:
      "<p>A large, industrious country with bountiful resources, stunning natural beauty, and world-renowned pretzels. To the north, you spot a breathtaking mountain range called the Alps, and to the south, the freezing, wind-tossed North Sea crashes into the rocky... shore...</p><p>Wait, hold up, that can't be right. The North Sea is in the south? Hmm.</p><p>You take a moment to consult your compass.</p><p>Well, that's odd.</p>Fifteen minutes later, with the aid of a friendly German man who sees you're confused and comes over to help, you figure out that the damned compass is busted somehow. According to Jürgen, the Alps are \"definitely\" in the South. Well, guess it's time to get a new compass. Thanks, Jürgen!</p>",
    objects: [
      {
        name: "CHECKPOINT CHARLIE",
        article: "",
        description:
          "A crossing point between East and West Berlin, from the days when the city was  divided by a big wall.",
      },
      {
        name: "BLACK FOREST",
        article: "The",
        description:
          "A fairytale forest stuffed with soaring pine trees and quaint old towns. This place seems friendly, but you get the sense they don't like outsiders asking too many questions about how they make their famous ham.",
      },
      {
        name: "LIMES GERMANICUS",
        article: "The",
        description:
          "A 600-km long line of ancient Roman fortifications. Currently, only about half the forts remain in active use by Roman legionnary forces.",
      },
      {
        name: "BEER",
        article: "",
        description:
          "As wine is to the French, and tea to the British, so is beer to the Germans. If you ask for wine or tea at a bar in Germany, they'll pretend not to have heard you, and serve you a big old stein of beer instead. After that, if you repeat your original order, you are considered a nuisance.",
      },
      {
        name: "CHARLEMAGNE'S THRONE",
        article: "",
        description:
          "Located in Aachen Cathedral, this throne has been the favorite chair of 31 different kings of Germany. Charlemagne himself is buried nearby, and some say this throne is so nice that his ghost still rises of a dark midnight, just to spend some time sitting on it again.",
      },
      {
        name: "JÜRGEN",
        article: "",
        description:
          "A German man, roughly 36 years old, wearing an orange shirt, and holding a free compass he just got.",
      },
    ],
    neighbors: [
      "Atlantic Ocean",
      "Austria",
      "Belgium",
      "Czech Republic",
      "Denmark",
      "France",
      "Luxembourg",
      "Netherlands",
      "Poland",
      "Switzerland",
    ],
  },
  {
    area: "Ghana",
    type: "country",
    neighbors: ["Atlantic Ocean", "Burkina Faso", "Côte d'Ivoire", "Togo"],
  },
  {
    area: "Greece",
    type: "country",
    neighbors: ["Albania", "Atlantic Ocean", "Bulgaria", "North Macedonia", "Turkey"],
  },
  {
    area: "Greenland",
    type: "country",
    description:
      "Fans of large islands have found what they're looking for: Greenland is the biggest island in the entire world, bar none. It is cold here. In the distance, you see a factory powering the economy by exporting shrimp and halibut, and groups of tourists enjoying themselves in the capitol city of Nuuk.",
    objects: [
      {
        name: "SHRIMP",
        article: "Some",
        description:
          "A crustacean stares up at you with long, gross eyes on disgusting, hateful stalks.",
      },
      {
        name: "RUNESTONE",
        article: "A",
        description:
          "This black chunk of star-metal is covered in ancient runes that throb with eldritch power.",
      },
    ],
    neighbors: ["Arctic Ocean", "Atlantic Ocean"],
  },
  {
    area: "Grenada",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Guatemala",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Belize",
      "El Salvador",
      "Honduras",
      "Mexico",
      "Pacific Ocean",
    ],
  },
  {
    area: "Guinea",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Côte d'Ivoire",
      "Guinea-Bissau",
      "Liberia",
      "Mali",
      "Senegal",
      "Sierra Leone",
    ],
  },
  {
    area: "Guinea-Bissau",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guinea", "Senegal"],
  },
  {
    area: "Guyana",
    type: "country",
    neighbors: ["Atlantic Ocean", "Brazil", "Suriname", "Venezuela"],
  },
  {
    area: "Haiti",
    type: "country",
    neighbors: ["Atlantic Ocean", "Dominican Republic"],
  },
  {
    area: "Honduras",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "El Salvador",
      "Guatemala",
      "Nicaragua",
      "Pacific Ocean",
    ],
  },
  {
    area: "Hong Kong",
    type: "special",
    neighbors: ["China", "Pacific Ocean"],
  },
  {
    area: "Hungary",
    type: "country",
    neighbors: [
      "Austria",
      "Croatia",
      "Romania",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Ukraine",
    ],
  },
  {
    area: "Iceland",
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean"],
  },
  {
    area: "India",
    type: "country",
    neighbors: [
      "Bangladesh",
      "Bhutan",
      "China",
      "Indian Ocean",
      "Myanmar",
      "Nepal",
      "Pakistan",
      "Sri Lanka",
    ],
  },
  {
    area: "Indonesia",
    type: "country",
    neighbors: [
      "East Timor",
      "Indian Ocean",
      "Malaysia",
      "Pacific Ocean",
      "Papua New Guinea",
    ],
  },
  {
    area: "Iran",
    type: "country",
    neighbors: [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Indian Ocean",
      "Iraq",
      "Pakistan",
      "Turkey",
      "Turkmenistan",
    ],
  },
  {
    area: "Iraq",
    type: "country",
    neighbors: [
      "Indian Ocean",
      "Iran",
      "Jordan",
      "Kuwait",
      "Saudi Arabia",
      "Syria",
      "Turkey",
    ],
  },
  {
    area: "Ireland",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Israel",
    type: "country",
    neighbors: ["Atlantic Ocean", "Egypt", "Indian Ocean", "Jordan", "Lebanon", "Syria"],
  },
  {
    area: "Italy",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Austria",
      "France",
      "San Marino",
      "Slovenia",
      "Switzerland",
      "Vatican City",
    ],
  },
  {
    area: "Jamaica",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Japan",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Jordan",
    type: "country",
    neighbors: ["Indian Ocean", "Iraq", "Israel", "Saudi Arabia", "Syria"],
  },
  {
    area: "Kazakhstan",
    type: "country",
    neighbors: ["China", "Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
  },
  {
    area: "Kenya",
    type: "country",
    neighbors: [
      "Ethiopia",
      "Indian Ocean",
      "Somalia",
      "South Sudan",
      "Tanzania",
      "Uganda",
    ],
  },
  {
    area: "Kiribati",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Library of Babel",
    description:
      "You are in a hexagonal gallery, surrounding an air shaft. On four sides of the hexagon there are book shelves filled with many similar-looking volumes. The other two sides lead into narrow hallways, beyond which are more galleries exactly like this one.",
    objects: [
      {
        name: "BOOK",
        article: "A",
        description: "It <em>seems</em> to be gibberish.",
      },
    ],
    type: "special",
    neighbors: ["Argentina", "Library of Babel"],
  },
  {
    area: "North Korea",
    type: "country",
    neighbors: ["China", "Pacific Ocean", "South Korea", "Russia"],
  },
  {
    area: "South Korea",
    type: "country",
    neighbors: ["North Korea", "Pacific Ocean"],
  },
  {
    area: "Kosovo",
    type: "country",
    neighbors: ["Albania", "Montenegro", "North Macedonia", "Serbia"],
  },
  {
    area: "Kuwait",
    type: "country",
    neighbors: ["Indian Ocean", "Iraq", "Saudi Arabia"],
  },
  {
    area: "Kyrgyzstan",
    type: "country",
    neighbors: ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
  },
  {
    area: "Laos",
    type: "country",
    neighbors: ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
  },
  {
    area: "Latvia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Belarus", "Estonia", "Lithuania", "Russia"],
  },
  {
    area: "Lebanon",
    type: "country",
    neighbors: ["Atlantic Ocean", "Israel", "Syria"],
  },
  {
    area: "Lesotho",
    type: "country",
    neighbors: ["South Africa"],
  },
  {
    area: "Liberia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guinea", "Côte d'Ivoire", "Sierra Leone"],
  },
  {
    area: "Libya",
    type: "country",
    neighbors: [
      "Algeria",
      "Atlantic Ocean",
      "Chad",
      "Egypt",
      "Niger",
      "Sudan",
      "Tunisia",
    ],
  },
  {
    area: "Liechtenstein",
    type: "country",
    neighbors: ["Austria", "Switzerland"],
  },
  {
    area: "Lithuania",
    description:
      "A temperate, thickly-forested, occasionally swampy land without significant mountain ranges to disrupt the flowering meadows and rolling fields of wheat and millet.",
    type: "country",
    objects: [
      {
        name: "ARTIS MAGNAE ARTILLERIAE",
        article: "A book labeled",
        description:
          "Kazimierz Siemienowic's classic artillery manual includes the first description of multi-stage rockets. Even though it's written in Latin from the 17th century, and you can't read a single word of it, you find yourself flipping through the entire volume. A real page-turner!",
      },
      {
        name: "SAINT CASIMIR'S FAIR",
        article: "",
        description:
          'You see roughly ten thousand people bustling through the streets of Vilnius, buying and selling arts and crafts, singing, and eating gingerbread. You stop to ask a Vilnian woman about the occasion, and she tells you it is a yearly celebration of the Feast of St. Casimir, held here for over three centuries, probably.<p>"Is it fun?" you ask.</p><p>"Yes," she shrugs.</p><p>You give her a big thumbs up and continue checking out the fair.</p>',
      },
    ],
    neighbors: ["Atlantic Ocean", "Belarus", "Latvia", "Poland", "Russia"],
  },
  {
    area: "Luxembourg",
    type: "country",
    neighbors: ["Belgium", "France", "Germany"],
  },
  {
    area: "Macau",
    type: "country",
    neighbors: ["China", "Pacific Ocean"],
  },
  {
    area: "Madagascar",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Madeira",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Malawi",
    type: "country",
    neighbors: ["Mozambique", "Tanzania", "Zambia"],
  },
  {
    area: "Malaysia",
    type: "country",
    neighbors: ["Brunei", "Indian Ocean", "Indonesia", "Pacific Ocean", "Thailand"],
  },
  {
    area: "Maldives",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Mali",
    type: "country",
    neighbors: [
      "Algeria",
      "Burkina Faso",
      "Côte d'Ivoire",
      "Guinea",
      "Mauritania",
      "Niger",
      "Senegal",
    ],
  },
  {
    area: "Malta",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Marshall Islands",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Mauritania",
    type: "country",
    neighbors: ["Algeria", "Atlantic Ocean", "Mali", "Senegal", "Western Sahara"],
  },
  {
    area: "Mauritius",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Mexico",
    type: "country",
    description:
      "It's hot here. As you pause for a moment to wipe the sweat from your brow, you can't help but see that Mexico is a country with many different people in it. Soon, your curiosity gets the better of you, and you stop in the shade of a SAGUARO CACTUS to watch them do the different kinds of things they are doing. You notice that sometimes they meet with success, but other times they do not. Yet, despite it all, they keep doing those things. What a remarkable country.",
    objects: [
      {
        name: "SAGUARO CACTUS",
        article: "A",
        description:
          'You must hold this cactus very cautiously, since it is covered in prickly, needlelike spines, called "spines" (or "needles") that can prick an incautious holder. This particular specimen is 12 feet tall, and 150 years old, making it both taller and older than any living basketball player.',
      },
      {
        name: "TEOTIHUACAN",
        article: "The city of",
        description:
          "A ruined complex with a stepped pyramid. You see that it was built by an ancient people, due to being old.",
      },
      {
        name: "AXOLOTL",
        article: "An",
        description:
          "A peculiar sort of salamander creature, native only to a few lakes around Mexico City. Unlike most people, it can regenerate its limbs.",
      },
      {
        name: "SPEARTHROWER OWL",
        article: "The",
        description:
          "A stone glyph, carved into the  shape of an owl holding a spear, it is the icon of an ancient Mayan king.",
      },
      {
        name: "TACO",
        article: "A",
        description:
          "It is an open-faced sandwich with meat, vegetables, and so on, traditionally eaten on Tuesdays.",
      },
    ],
    neighbors: [
      "Atlantic Ocean",
      "Belize",
      "Guatemala",
      "Pacific Ocean",
      "United States",
    ],
  },
  {
    area: "Federated States of Micronesia",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Moldova",
    type: "country",
    neighbors: ["Romania", "Ukraine"],
  },
  {
    area: "Monaco",
    type: "country",
    neighbors: ["Atlantic Ocean", "France"],
  },
  {
    area: "Mongolia",
    type: "country",
    neighbors: ["China", "Russia"],
  },
  {
    area: "Montenegro",
    type: "country",
    neighbors: [
      "Albania",
      "Atlantic Ocean",
      "Bosnia and Herzegovina",
      "Croatia",
      "Kosovo",
      "Serbia",
    ],
  },
  {
    area: "Morocco",
    type: "country",
    neighbors: ["Algeria", "Atlantic Ocean", "Western Sahara", "Spain"],
  },
  {
    area: "Mozambique",
    type: "country",
    neighbors: [
      "Eswatini",
      "Indian Ocean",
      "Malawi",
      "South Africa",
      "Tanzania",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    area: "Myanmar",
    type: "country",
    neighbors: ["Bangladesh", "China", "India", "Indian Ocean", "Laos", "Thailand"],
  },
  {
    area: "Namibia",
    type: "country",
    neighbors: ["Angola", "Atlantic Ocean", "Botswana", "South Africa", "Zambia"],
  },
  {
    area: "Nauru",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Nepal",
    type: "country",
    neighbors: ["China", "India"],
  },
  {
    area: "Netherlands",
    type: "country",
    neighbors: ["Atlantic Ocean", "Belgium", "Germany", "Saint Martin", "France"],
  },
  {
    area: "New Zealand",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Nicaragua",
    type: "country",
    neighbors: ["Atlantic Ocean", "Costa Rica", "Honduras", "Pacific Ocean"],
  },
  {
    area: "Niger",
    type: "country",
    neighbors: ["Algeria", "Benin", "Burkina Faso", "Chad", "Libya", "Mali", "Nigeria"],
  },
  {
    area: "Nigeria",
    type: "country",
    neighbors: ["Atlantic Ocean", "Benin", "Cameroon", "Chad", "Niger"],
  },
  {
    area: "North Macedonia",
    type: "country",
    neighbors: ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
  },
  {
    area: "Norway",
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean", "Finland", "Sweden", "Russia"],
  },
  {
    area: "Oman",
    type: "country",
    neighbors: ["Indian Ocean", "Saudi Arabia", "United Arab Emirates", "Yemen"],
  },
  {
    area: "Pakistan",
    type: "country",
    neighbors: ["Afghanistan", "India", "Indian Ocean", "Iran", "China"],
  },
  {
    area: "Palau",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Palestine",
    type: "country",
    neighbors: ["Atlantic Ocean", "Egypt", "Israel", "Jordan"],
  },
  {
    area: "Panama",
    type: "country",
    neighbors: ["Atlantic Ocean", "Colombia", "Costa Rica", "Pacific Ocean"],
  },
  {
    area: "Papua New Guinea",
    type: "country",
    neighbors: ["Indonesia", "Pacific Ocean"],
  },
  {
    area: "Paraguay",
    type: "country",
    neighbors: ["Argentina", "Bolivia", "Brazil"],
  },
  {
    area: "Peru",
    type: "country",
    neighbors: ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Pacific Ocean"],
  },
  {
    area: "Philippines",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Poland",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Belarus",
      "Czech Republic",
      "Germany",
      "Lithuania",
      "Russia",
      "Slovakia",
      "Ukraine",
    ],
  },
  {
    area: "Portugal",
    type: "country",
    neighbors: ["Atlantic Ocean", "Spain"],
  },
  {
    area: "Qatar",
    type: "country",
    neighbors: ["Indian Ocean", "Saudi Arabia"],
  },
  {
    area: "Romania",
    type: "country",
    neighbors: ["Atlantic Ocean", "Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
  },
  {
    area: "Russia",
    type: "country",
    description:
      "Straddling eleven timezones across Europe and Asia, Russia is an incredibly large place, full of beautiful scenery and generous people. You set out to explore the vast land and its rich history, from vikings, to revolution, to mass starvation, to kleptocracy.",
    objects: [
      {
        name: "VODKA",
        article: "Some",
        description:
          "A potato-based liquor, believed to make life tolerable despite evidence to the contrary. ",
      },
      {
        name: "AK-47",
        article: "An",
        description:
          "An automatic rifle designed by  Mikhail Kalashnikov in 1947, but still in production and wide use today. When you absolutely, positively have to provide a cheap and reliable weapon to every soldier in your army, accept no substitutes.",
      },
      {
        name: "SPUTNIK",
        article: "",
        description:
          "This robot jellyfish was thought to have burned up upon re-entry, after completing its mission in 1958, but you happen to spot the remnants in a bush just outside Moscow. Remarkably, it is still intact, though one of its four antennae is slightly bent.",
      },
      {
        name: "KRUSHCHYOVKA",
        article: "A dingy, gray",
        description:
          "Apartments made out of prefabricated concrete pieces, used to quickly erect inexpensive housing for the masses. As you wander around Russia, you spot hundreds of these buildings, some still standing since the 1960s.",
      },
    ],
    neighbors: [
      "Abkhazia",
      "Arctic Ocean",
      "Atlantic Ocean",
      "Azerbaijan",
      "Belarus",
      "China",
      "Estonia",
      "Finland",
      "Georgia",
      "Kazakhstan",
      "Latvia",
      "Lithuania",
      "Mongolia",
      "North Korea",
      "Norway",
      "Pacific Ocean",
      "Poland",
      "South Ossetia",
      "Tuva",
      "Ukraine",
    ],
  },
  {
    area: "Rwanda",
    type: "country",
    neighbors: ["Burundi", "Democratic Republic of the Congo", "Tanzania", "Uganda"],
  },
  {
    area: "Saint Kitts and Nevis",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saint Lucia",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saint Vincent and the Grenadines",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Samoa",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "San Marino",
    description:
      "On a mountain overlooking this tiny city state, you see three medieval towers rising picturesquely into the blue skies.",
    type: "country",
    objects: [
      {
        name: "GUAITA",
        article: "The",
        description:
          "The oldest of the three towers of San Marino, this one was built as a prison in the 11th century.",
      },
      {
        name: "CESTA",
        article: "The",
        description:
          "The tallest of the three towers of San Marino, this one looks like it's wearing a hat.",
      },
      {
        name: "MONTALE",
        article: "The",
        description:
          '<p>The most mysterious of the three towers of San Marino, this one cannot be entered by the public, and the only entrance is a single door located 20 feet off the ground.</p><p>"What do you think is inside the Montale?" you ask a passer-by.<br/>"I heard it\'s where the Pope keeps his pterodactyls", she says, lowering her voice to nearly a whisper and glancing furtively around the train station.',
      },
      {
        name: "TORTA TRE MONTI",
        article: "A",
        description:
          "A type of cake, made to celebrate those three beautiful towers in San Marino. As you munch on a slice, you have to admit that this combination of waffle substrate and chocolate cement truly captures the essence of the city's most famous symbols.",
      },
    ],
    neighbors: ["Italy"],
  },
  {
    area: "São Tomé and Príncipe",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Saudi Arabia",
    type: "country",
    neighbors: [
      "Indian Ocean",
      "Iraq",
      "Jordan",
      "Kuwait",
      "Oman",
      "Qatar",
      "United Arab Emirates",
      "Yemen",
    ],
  },
  {
    area: "Scotland",
    type: "country",
    neighbors: ["Atlantic Ocean", "England"],
  },
  {
    area: "Senegal",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Gambia",
      "Guinea-Bissau",
      "Guinea",
      "Mali",
      "Mauritania",
    ],
  },
  {
    area: "Serbia",
    type: "country",
    neighbors: [
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Hungary",
      "Kosovo",
      "Montenegro",
      "North Macedonia",
      "Romania",
    ],
  },
  {
    area: "Seychelles",
    type: "country",
    neighbors: ["Indian Ocean"],
  },
  {
    area: "Sierra Leone",
    type: "country",
    neighbors: ["Atlantic Ocean", "Guinea", "Liberia"],
  },
  {
    area: "Singapore",
    type: "country",
    neighbors: ["Indian Ocean", "Pacific Ocean"],
  },
  {
    area: "Slovakia",
    type: "country",
    neighbors: ["Austria", "Czech Republic", "Hungary", "Poland", "Ukraine"],
  },
  {
    area: "Slovenia",
    type: "country",
    neighbors: ["Atlantic Ocean", "Austria", "Croatia", "Italy", "Hungary"],
  },
  {
    area: "Solomon Islands",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Somalia",
    type: "country",
    neighbors: ["Djibouti", "Ethiopia", "Indian Ocean", "Kenya"],
  },
  {
    area: "South Africa",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Botswana",
      "Eswatini",
      "Indian Ocean",
      "Lesotho",
      "Mozambique",
      "Namibia",
      "Zimbabwe",
    ],
  },
  {
    area: "South Ossetia",
    type: "country",
    neighbors: ["Russia", "Georgia"],
  },
  {
    area: "South Sudan",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Democratic Republic of the Congo",
      "Ethiopia",
      "Kenya",
      "Sudan",
      "Uganda",
    ],
  },
  {
    area: "Spain",
    type: "country",
    neighbors: [
      "Atlantic Ocean",
      "Andorra",
      "France",
      "Portugal",
      "Gibraltar",
      "Morocco",
    ],
  },
  {
    area: "Sri Lanka",
    type: "country",
    neighbors: ["India", "Indian Ocean"],
  },
  {
    area: "Sudan",
    type: "country",
    neighbors: [
      "Central African Republic",
      "Chad",
      "Egypt",
      "Eritrea",
      "Ethiopia",
      "Indian Ocean",
      "Libya",
      "South Sudan",
    ],
  },
  {
    area: "Suriname",
    type: "country",
    neighbors: ["Atlantic Ocean", "Brazil", "French Guiana", "Guyana"],
  },
  {
    area: "Svalbard",
    type: "special",
    neighbors: ["Atlantic Ocean", "Brazil", "French Guiana", "Guyana"],
  },
  {
    area: "Sweden",
    type: "country",
    neighbors: ["Atlantic Ocean", "Finland", "Norway"],
  },
  {
    area: "Switzerland",
    type: "country",
    neighbors: ["Austria", "France", "Germany", "Italy", "Liechtenstein"],
  },
  {
    area: "Syria",
    type: "country",
    neighbors: ["Atlantic Ocean", "Iraq", "Israel", "Jordan", "Lebanon", "Turkey"],
  },
  {
    area: "Taiwan",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Tajikistan",
    type: "country",
    neighbors: ["Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"],
  },
  {
    area: "Tanzania",
    type: "country",
    neighbors: [
      "Burundi",
      "Democratic Republic of the Congo",
      "Indian Ocean",
      "Kenya",
      "Malawi",
      "Mozambique",
      "Rwanda",
      "Uganda",
      "Zambia",
    ],
  },
  {
    area: "Tasmania",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Thailand",
    type: "country",
    neighbors: [
      "Cambodia",
      "Indian Ocean",
      "Laos",
      "Malaysia",
      "Myanmar",
      "Pacific Ocean",
    ],
  },
  {
    area: "Togo",
    type: "country",
    neighbors: ["Benin", "Burkina Faso", "Ghana"],
  },
  {
    area: "Tonga",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Trinidad and Tobago",
    type: "country",
    neighbors: ["Atlantic Ocean"],
  },
  {
    area: "Tunisia",
    type: "country",
    neighbors: ["Algeria", "Libya"],
  },
  {
    area: "Turkey",
    type: "country",
    neighbors: [
      "Armenia",
      "Atlantic Ocean",
      "Azerbaijan",
      "Bulgaria",
      "Georgia",
      "Greece",
      "Iran",
      "Iraq",
      "Syria",
    ],
  },
  {
    area: "Turkmenistan",
    type: "country",
    neighbors: ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan"],
  },
  {
    area: "Tuva",
    description:
      "A small republic, known for its stamps and throat singing. Its flag is a Y on its side, in blue and yellow.",
    type: "special",
    neighbors: ["Mongolia", "Russia"],
    objects: [
      {
        name: "RICHARD FEYNMAN",
        article: "The ghost of",
        description:
          "You see a translucent man of medium build with dark hair and a mischievous smile. He seems to be playing a pair of bongos. When you catch his eye, he fades into the sunlight and is gone.",
      },
    ],
  },
  {
    area: "Tuvalu",
    type: "country",
    description:
      "A series of small volcanic islands, with a nice coral reef. At its high point, it's only about 15 feet above the water.",
    neighbors: ["Pacific Ocean"],
    objects: [
      {
        name: "COCONUT",
        article: "A",
        description:
          "<p>What's smaller than a bowling ball, and covered with hair? Plenty of things: Kittens, moles, wigs. One thing that's not covered with hair, though, is a coconut: the short, bristly husk is not actually \"hair\" at all, it's a plant!</p><p>And despite urban legends to the contrary, falling coconuts do not kill hundreds of people a year, or cause temporary amnesia.</p>",
      },
    ],
  },
  {
    area: "Uganda",
    type: "country",
    neighbors: [
      "Democratic Republic of the Congo",
      "Kenya",
      "Rwanda",
      "South Sudan",
      "Tanzania",
    ],
  },
  {
    area: "Ukraine",
    type: "country",
    neighbors: [
      "Belarus",
      "Hungary",
      "Moldova",
      "Poland",
      "Romania",
      "Russia",
      "Slovakia",
    ],
  },
  {
    area: "United Arab Emirates",
    type: "country",
    neighbors: ["Indian Ocean", "Oman", "Saudi Arabia"],
  },
  {
    area: "United States",
    description:
      'A large and diverse country, it is home to the famous "50 state quarters" phenomenon of the early 2000s. You see a BALD EAGLE fishing the many lakes, rivers, and ponds here.',
    type: "country",
    neighbors: ["Arctic Ocean", "Atlantic Ocean", "Canada", "Mexico", "Pacific Ocean"],
    objects: [
      {
        name: "GRAND CANYON",
        article: "The",
        description: "A canyon, roughly 277 miles long, 18 miles wide, and 1 mile deep.",
      },
      {
        name: "LIBERTY BELL",
        article: "The",
        description: "A large bell containing the sound of freedom",
      },
      {
        name: "BALD EAGLE",
        article: "A",
        description:
          "This large bird has a white head, dark body, yellow beak, and pink tongue. Most often found in wooded areas, they can sometimes be seen flying in front of waving flags or at fireworks shows. In addition to fish, bald eagles are the primary predator of raccoons.",
      },
      {
        name: "IDAHO POTATO",
        article: "An",
        description: "A small tuber, covered in dirt.",
      },
    ],
  },
  {
    area: "Uruguay",
    type: "country",
    neighbors: ["Argentina", "Atlantic Ocean", "Brazil"],
  },
  {
    area: "Uzbekistan",
    type: "country",
    neighbors: ["Afghanistan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan"],
  },
  {
    area: "Vanuatu",
    type: "country",
    neighbors: ["Pacific Ocean"],
  },
  {
    area: "Vatican City",
    type: "country",
    neighbors: ["Italy"],
  },
  {
    area: "Venezuela",
    type: "country",
    neighbors: ["Atlantic Ocean", "Brazil", "Colombia", "Guyana"],
  },
  {
    area: "Vietnam",
    type: "country",
    neighbors: ["Cambodia", "China", "Laos", "Pacific Ocean"],
  },
  {
    area: "Wallis Island",
    type: "country",
    neighbors: ["Pacific Ocean"],
    objects: [
      {
        name: "TALIETUMU",
        article: "A pile of rocks known as",
        description:
          "An elevated platform made of rocks, built in the days of Tu'i Tonga empire.",
      },
      {
        name: "ROBERT",
        article: "Someone named",
        description: "This man is programming on a computer.",
      },
    ],
  },
  {
    area: "Wales",
    type: "country",
    neighbors: ["Atlantic Ocean", "England"],
  },
  {
    area: "Western Sahara",
    type: "country",
    neighbors: ["Algeria", "Mauritania", "Morocco"],
  },
  {
    area: "Yemen",
    type: "country",
    neighbors: ["Indian Ocean", "Oman", "Saudi Arabia"],
  },
  {
    area: "Zambia",
    type: "country",
    neighbors: [
      "Angola",
      "Botswana",
      "Democratic Republic of the Congo",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Tanzania",
      "Zimbabwe",
    ],
  },
  {
    area: "Zimbabwe",
    type: "country",
    neighbors: ["Botswana", "Mozambique", "South Africa", "Zambia"],
  },
];
